### ISSUE TITLE
The text result got wrong

### ISSUE THREAD

**Issue by ivansuharyadi** [thiagoalessio/tesseract-ocr-for-php#103]
My code :
![code](https://user-images.githubusercontent.com/4571528/34876559-b00ffa4e-f7d4-11e7-8224-9db929a8d5e0.jpg)
Image Sources:
![struk](https://user-images.githubusercontent.com/4571528/34876508-6ec3680a-f7d4-11e7-93e1-99dc937d4b8f.jpg)

Results :
![results](https://user-images.githubusercontent.com/4571528/34876560-b0492f08-f7d4-11e7-9669-3d52e7d862c8.jpg)

### Expected behavior

Got text results according the images 

### Actual behavior

Got wrong text

#### Environment

* **Operating system:**

        Windows 7

* **PHP version:**

       PHP 5.6

* **Tesseract version:**

        3.05.01

* **tesseract-ocr-for-php version:**

       2.1.0

**Comment by thiagoalessio** [comment]
This is a a problem you are having with the usage of tesseract, not an issue of this library.

Keep in mind that what I offer is *only* a wrapper to execute tesseract commands from PHP, nothing beyond that.

Try to learn what kinds of tesseract options make the recognition correct, and then you can use this wrapper accordingly.

**Comment by ivansuharyadi** [comment]
Ahh youre right, Thanks @thiagoalessio
