### ISSUE TITLE
Feature Request: Add TSV and HOCR support.

### ISSUE THREAD

**Issue by rhys-mcguckin** [thiagoalessio/tesseract-ocr-for-php#104]
I'd like to export the data in either TSV or HOCR support.

This should be as simple as adding a ->format('tsv') function, which adds that to the end of the command-line.

**Comment by thiagoalessio** [comment]
Hello @rhys-mcguckin , thank you for your contribution. This proposal seems like a nice addition to the project. I'll evaluate further and come back to you ;D

**Comment by rhys-mcguckin** [comment]
I was thinking based on the design you already have you could add classes for formats, so Text, Tsv, Hocr, and use a similar isFormat(), in the build command (defaulting to straight text when no format specified).

If you are interested in this as an option, I'm fine to do up a pull request.
