### ISSUE TITLE
请问如何识别多行文字？

### ISSUE THREAD

**Issue by linxiaojialin** [thiagoalessio/tesseract-ocr-for-php#106]
### Expected behavior

你好，我用你的框架只能识别图片中间的一行文字，请问这个框架能否识别一张图片上的多行文字呢？如果能，我该如何使用？

#### Environment

* **Operating system:**

  Windows10

* **PHP version:**

   php 7.0.13

* **Tesseract version:**

   tesseract 3.05.00dev

* **tesseract-ocr-for-php version:**

    thiagoalessio/tesseract_ocr 2.2.0

**Comment by talessio-adaccamping** [comment]
Please post your issue in English, so that I will be able to help you and it becomes useful for other users facing a similar issue.

**Comment by thiagoalessio** [comment]
Please post your issue in English, so that I will be able to help you and it becomes useful for other users facing a similar issue.

**Comment by thiagoalessio** [comment]
Closing for now, please reopen it once you translate, ok?

**Comment by linxiaojialin** [comment]
I'm sorry for the delay in replying because of the holiday.
I will submit it once again after I have translated it into English, but the translation may not be very smooth.

**Comment by thiagoalessio** [comment]
Continuing our discussion on #109
