### ISSUE TITLE
text file is not generating on live website

### ISSUE THREAD

**Issue by poojark66** [thiagoalessio/tesseract-ocr-for-php#11]
my execute command
 protected function execute()
    {
		$path = getenv('PATH');
		putenv("PATH=$path:/usr/local/bin/tesseract ");
		
		$pathtess = $path."/tessdata";
                 $this->outputFile = rand();
		 echo $this->buildTesseractCommand();
                 exec($this->buildTesseractCommand(),$pathtess);
    }

**Comment by thiagoalessio** [comment]
too bad for you ...

**Comment by big89** [comment]
same problem with me . need urgent solution
