### ISSUE TITLE
Empty Result

### ISSUE THREAD

**Issue by akhilmeakkadn2** [thiagoalessio/tesseract-ocr-for-php#110]
Hi,
I am getting empty result while using run function.
I am installed terreract ocr binary v3.05 via exe file. I am using windows 10 and  wamp server with php 5.6.

code:
include "vendor/autoload.php";
use thiagoalessio\TesseractOCR\TesseractOCR;
$k =  (new TesseractOCR('text.png'))
    ->run();
var_dump($k);

Thanks in advance.

**Comment by jdbolts** [comment]
How did you resolve this issue?

**Comment by akhilmeakkadn2** [comment]
![tesseract](https://user-images.githubusercontent.com/30225241/37383085-6fa76df8-276c-11e8-887c-105ae7655607.png)

**Comment by akhilmeakkadn2** [comment]
Please find the code and use php 5.6 or above with tesseract 3.4. This is working fine for me on windows.
