### ISSUE TITLE
improve image process

### ISSUE THREAD

**Issue by quyeticb** [thiagoalessio/tesseract-ocr-for-php#112]
I write simple break captcha, but captcha is not correct
Here is my code
`

	require_once(__DIR__ .'/vendor/autoload.php');
	use thiagoalessio\TesseractOCR\TesseractOCR;
	
	exec('convert -units PixelsPerInch source.jpg -density 300 step1.png');
	exec('convert -colorspace gray -modulate 120 -contrast-stretch 10%x80% -modulate 140 -gaussian-blur 1 -contrast-stretch 5%x50% +repage -negate -gaussian-blur 4 -negate -modulate 130 step1.png target.png');
	$a=new TesseractOCR('clean.png');
	$a->whitelist(range('A', 'Z'));
	$a->lang('eng');
	$result=$a->run();
	print_r($result.PHP_EOL);`

My Image: https://snag.gy/Oy0Puj.jpg
need improve it.
thanks!

**Comment by thiagoalessio** [comment]
That's not the place to ask for it, please just open issues if you found a bug or missing functionality on the wrapper.
