### ISSUE TITLE
Get image confidence score with php

### ISSUE THREAD

**Issue by Paquitoo** [thiagoalessio/tesseract-ocr-for-php#113]
Hi all,
I try to get the confidence score of an image extracted text, I know it's possible with tesseract but I didn't find any working way with php. Is there a possibility to get that ?
Thanks you !

Last  2018  tesseract ocr for php version installed on Debian Jessie

**Comment by thiagoalessio** [comment]
Hello!
Sure, if it works through the command line I can write something to support it via PHP ... you just need to share the exact tesseract command you used to get this score and the output it generated ;D

**Comment by thiagoalessio** [comment]
@Paquitoo ping

**Comment by Paquitoo** [comment]
Hi !
Thanks for your fast response thiagoalessio !
Her is the code used to get the table with confidence level : 
`tesseract  --tessdata-dir ./ ./testing/eurotext.png ./testing/eurotext-eng -l eng tsv`
that i saw her : [https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage#tsv-output-currently-available-in-305-dev-in-master-branch-on-github](https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage#tsv-output-currently-available-in-305-dev-in-master-branch-on-github)

!!
!!
!!

Oh I'm sorry, I just saw that you already wrote TSV support but when I use it I got an error : 
 
> **Notice: Undefined offset: 0 in /var/www/clients/client0/web5/web/lib/tesseract/TesseractOCR.php on line 46**
> string(50) "You could be allergic to dinosaurs and never know."


this is my code : 

```
<?php
include ("../lib/tesseract/Command.php");
include ('../lib/tesseract/Option/Config.php');
include ("../lib/tesseract/TesseractOCR.php");

use thiagoalessio\TesseractOCR\TesseractOCR;

$result = (new TesseractOCR('../wp-content/uploads/2018/03/gag.jpg'))
	->tsv()
	->run();
	
var_dump($result);
```

Thank you again for your answer !

**Comment by thiagoalessio** [comment]
:laughing: hahahahaha that is the best `var_dump` **ever**
> `string(50) "You could be allergic to dinosaurs and never know."`

Thanks for the feedback. This notice is definitely some case I missed .... will fix that ASAP and let you know ;D

**Comment by thiagoalessio** [comment]
Found the problem: I just noticed that you are manually including files, you just missed some.
```
include ('../lib/tesseract/Option/Format.php');
include ('../lib/tesseract/Shortcut/Tsv.php');
```
Just Include them and everything will work fine ;D

**Comment by Paquitoo** [comment]
Thanks !
I'm really sorry to have make loose your time for this...
No more error but
```
echo (new TesseractOCR('../wp-content/uploads/2018/03/gag.jpg'))
    ->format('tsv')
    ->run();
```
or 
```
echo (new TesseractOCR('../wp-content/uploads/2018/03/gag.jpg'))
    ->tsv()
    ->run();
```
return me just the extracted text, like if **tsv()** didn't change anything, and no way to echo the tsv table.
I'll try to resolve this by myself, anyway, thaks for your previous answers !!
Have a nice day :)
Paco

**Comment by thiagoalessio** [comment]
Hi, that happens when your tesseract version is smaller than 3.05 (there was no TSV before that)

You said you are on debian jessie, right? Double check the package version, that might be the issue

**Comment by Paquitoo** [comment]
Oh okay, thanks !
That's it, I have 3.03, but when i try to upgrade It say that it's the lastest version... strange haha
I'll find another solution !
Thanks for all, again, Thiagoalessio !

**Comment by thiagoalessio** [comment]
@Paquitoo just out of curiosity: why are you manually including the files instead of using an autoloader?

**Comment by Paquitoo** [comment]
@thiagoalessio Hey
Sorry for the late answer, I'm not familiar with git and all of this, so I must admit I don't even know that was possible and how to do haha !
My english is not very good so I can be easily loosed in all of this :)
