### ISSUE TITLE
can't return text

### ISSUE THREAD

**Issue by lovekobeme** [thiagoalessio/tesseract-ocr-for-php#114]
i try many times and many ways to convert img to text, but just return string(0) "", what is wrong on my code?
(phpversion-5.6)
require_once './vendor/autoload.php';
use thiagoalessio\TesseractOCR\TesseractOCR;
$res= (new TesseractOCR('text.png'))
    ->run();
 var_dump($res)
or
	// require_once './vendor/autoload.php';
include ("./vendor/thiagoalessio/tesseract_ocr/src/Command.php");
include ('./vendor/thiagoalessio/tesseract_ocr/src/Option/Config.php');
include ("./vendor/thiagoalessio/tesseract_ocr/src/TesseractOCR.php");
include ('./vendor/thiagoalessio/tesseract_ocr/src/Option/Format.php');
include ('./vendor/thiagoalessio/tesseract_ocr/src/Shortcut/Whitelist.php');
use thiagoalessio\TesseractOCR\TesseractOCR;
// var_dump (new TesseractOCR(''));

$res= (new TesseractOCR('text.png'))
    ->run();
 var_dump($res)

[test.zip](https://github.com/thiagoalessio/tesseract-ocr-for-php/files/1862019/test.zip)

cmd.exe install Capture2Text  information

The use of .nupkg or .nuspec in for package name or source is known to cause i
ues. Please use the package id from the nuspec `<id />` with `-s .` (for local
older where nupkg is found).
Chocolatey v0.10.9

Installing the following packages:
1.nupkg
By installing you accept licenses for the packages.

capture2text v3.9
capture2text package files install completed. Performing other installation st
s.
The package capture2text wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): y

Downloading capture2text
  from 'https://sourceforge.net/projects/capture2text/files/Capture2Text/Captu
2Text_v3.9/Capture2Text_v3.9.zip'
Progress: 100% - Completed download of C:\Users\Administrator\AppData\Local\Te
\chocolatey\capture2text\3.9\Capture2Text_v3.9.zip (56.52 MB).
Download of Capture2Text_v3.9.zip (56.52 MB) completed.
Hashes match.
Extracting C:\Users\Administrator\AppData\Local\Temp\chocolatey\capture2text\3
\Capture2Text_v3.9.zip to C:\ProgramData\chocolatey\lib\capture2text\tools...
C:\ProgramData\chocolatey\lib\capture2text\tools
 ShimGen has successfully created a shim for Capture2Text.exe
 ShimGen has successfully created a shim for leptonica_util.exe
 ShimGen has successfully created a shim for tesseract.exe
 The install of capture2text was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\capture2text\tools'

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

**Comment by thiagoalessio** [comment]
Please use the appropriate channels to get help: https://github.com/thiagoalessio/tesseract-ocr-for-php#where-to-get-help
Issues are meant to report bugs found on the library.
