### ISSUE TITLE
PHP Warning:  exec(): NULL byte detected. Possible attack 

### ISSUE THREAD

**Issue by juragandotid** [thiagoalessio/tesseract-ocr-for-php#117]
this is my code : 
`
include 'vendor/autoload.php';
	
	use thiagoalessio\TesseractOCR\TesseractOCR;
	
	function captcha($url) {
		header("Content-Type: image/jpeg");
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_POST, 0);
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_HEADER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_COOKIEFILE, getcwd() . "/cookies.txt");
        curl_setopt($ch, CURLOPT_COOKIEJAR, getcwd() . "/cookies.txt");
        curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36");

        $result = curl_exec($ch);
        curl_close($ch);

        return $result;
    }

	
	$captcha   = captcha("https://example.com/index.php/register/captcha/login");
	
	echo(new TesseractOCR($captcha))->whitelist(range(0, 9), range('A', 'Z'))->run();
`
but i get some error : 

PHP Warning:  exec(): NULL byte detected. Possible attack in F:\ocr\vendor\thiagoalessio\tesseract_ocr\src\TesseractOCR.php on line 18

Warning: exec(): NULL byte detected. Possible attack in F:\ocr\vendor\thiagoalessio\tesseract_ocr\src\TesseractOCR.php on line 18
PHP Warning:  join(): Invalid arguments passed in F:\ocr\vendor\thiagoalessio\tesseract_ocr\src\TesseractOCR.php on line 19

Warning: join(): Invalid arguments passed in F:\ocr\vendor\thiagoalessio\tesseract_ocr\src\TesseractOCR.php on line 19

captcha format like this : c4u

Can u explain why i get this error and what  can i do?

Thank you.

**Comment by thiagoalessio** [comment]
Hello @juragandotid 

Please provide the information requested on the [issue template](https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/master/.github/issue_template.md) (it appeared to you when you were opening it). Otherwise is quite difficult to isolate the potential issue.

**Comment by thiagoalessio** [comment]
@juragandotid ping, still having the issue ?? please let me know ;D

**Comment by juragandotid** [comment]
![untitled](https://user-images.githubusercontent.com/35671934/38713657-40905ac0-3ea0-11e8-8a60-4d45f486c1db.png)

i'm already install tesseract for windows but it still got an error like thi : 
`HP Warning:  exec(): NULL byte detected. Possible attack in F:\ocr\vendor\thiagoalessio\tesseract_ocr\src\TesseractOCR.php on line 18

Warning: exec(): NULL byte detected. Possible attack in F:\ocr\vendor\thiagoalessio\tesseract_ocr\src\TesseractOCR.php on line 18
PHP Warning:  join(): Invalid arguments passed in F:\ocr\vendor\thiagoalessio\tesseract_ocr\src\TesseractOCR.php on line 19

Warning: join(): Invalid arguments passed in F:\ocr\vendor\thiagoalessio\tesseract_ocr\src\TesseractOCR.php on line 19`

this is my source : 
`include 'vendor/autoload.php';
	
	use thiagoalessio\TesseractOCR\TesseractOCR;
	
	function captcha($url) {
		header("Content-Type: image/jpeg");
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_POST, 0);
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_HEADER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_COOKIEFILE, getcwd() . "/cookies.txt");
        curl_setopt($ch, CURLOPT_COOKIEJAR, getcwd() . "/cookies.txt");
        curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36");

        $result = curl_exec($ch);
		curl_close($ch);
		
        return $result;
    }

	
	$captcha   = captcha("https://my.store.test/index.php/register/captcha/login");	
	
	echo(new TesseractOCR($captcha))->whitelist(range(0, 9), range('A', 'Z'))->run();`

can u help me to fix it? 

Thank you.

**Comment by thiagoalessio** [comment]
@juragandotid sure I can help, but to do so I need you to fill out the issue template: https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/master/.github/issue_template.md

**Comment by thiagoalessio** [comment]
@juragandotid I just found out that the latest versions of `capture2text` are no longer offering the `tesseract` binary.
Just updated the README alerting to that, maybe it is the reason for your issue: https://github.com/thiagoalessio/tesseract-ocr-for-php#-note-for-windows-users

**Comment by thiagoalessio** [comment]
@juragandotid as it seems, there is nothing wrong with the wrapper itself. you simply lack tesseract in your environment.
