### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by BergLars** [thiagoalessio/tesseract-ocr-for-php#118]
* **Operating system:**

 macOS 10.10.

* **PHP version:**

 PHP 5.5.38

* **Tesseract version:**

 tesseract 3.05.01
 leptonica-1.75.3
 libjpeg 9c : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.5

* **tesseract-ocr-for-php version:**

name     : thiagoalessio/tesseract_ocr
descrip. : A wrapper to work with Tesseract OCR inside PHP.
keywords : OCR, Tesseract, text recognition
versions : * 2.0.0
type     : library
license  : Apache License 2.0 (Apache-2.0) (OSI approved) https://spdx.org/licenses/Apache-2.0.html#licenseText
source   : [git] https://github.com/thiagoalessio/tesseract-ocr-for-php.git 0e91eb357946c71fadc92d9493c87d56dee63d96
dist     : [zip] https://api.github.com/repos/thiagoalessio/tesseract-ocr-for-php/zipball/0e91eb357946c71fadc92d9493c87d56dee63d96 0e91eb357946c71fadc92d9493c87d56dee63d96
names    : thiagoalessio/tesseract_ocr

* **Issue:**

Im getting the following error messages:
array(3) {
  [0]=>
  string(68) "dyld: Library not loaded: /usr/local/opt/libtiff/lib/libtiff.5.dylib"
  [1]=>
  string(63) "  Referenced from: /usr/local/opt/leptonica/lib/liblept.5.dylib"
  [2]=>
  string(131) "  Reason: Incompatible library version: liblept.5.dylib requires version 9.0.0 or later, but libtiff.5.dylib provides version 6.0.0"
}

Code:
```
exec('/usr/local/Cellar/tesseract/3.05.01/bin/tesseract -v 2>&1', $out);
var_dump($out);

or

use thiagoalessio\TesseractOCR\TesseractOCR;

echo (new TesseractOCR(__DIR__.'/text.png'))
	->run();
```

and i changed your run function to this:
```
	public function run()
	{
		exec($this->buildCommand()." 2>&1", $output);
		echo "<pre>";
		var_dump($output);
		echo "</pre>";

		return trim(join(PHP_EOL, $output));
	}

```
this only happens using the exec() command (or after adding ." 2>&1" to the command inside the exec() in the run function), since the tesseract command itself could be found, i'm not quite sure how to resolve this problem.

Using the command on the command line also works flawlessly.

I'm running the server localy with XAMPP, i've made sure permissions and PATH are set correctly and I've tried to update all dependencies (using Homebrew) with no success.

can anyone help me out?
thanks in advance

Edit: I'm aware that this problem isn't caused by the wrapper however I really could use some help from someone who knows what he's doing.

**Comment by thiagoalessio** [comment]
Hello @BergLars !

> Edit: I'm aware that this problem isn't caused by the wrapper however I really could use some help from someone who knows what he's doing.

No problem, I'm actually compiling a list of common tesseract issues found by the users of this wrapper, so I don't need to answer it multiple times on Gitter 😛 

Thanks for filling out the issue details, I will try to reproduce it tonight and will let you know my findings.

**Comment by thiagoalessio** [comment]
@BergLars quick question: how did you install Tesseract? via homebrew, ports, something else?

**Comment by thiagoalessio** [comment]
@BergLars Sorry, but this open issue is bothering me a bit ... I'd like to invite you to continue this conversation with me on Gitter (https://gitter.im/thiagoalessio/tesseract-ocr-for-php)
Once you have some time, please let me know how you installed tesseract on your env, for me to reproduce this problem ;D
