### ISSUE TITLE
read_params_file cannot open 7

### ISSUE THREAD

**Issue by teamcoltra** [thiagoalessio/tesseract-ocr-for-php#119]
*IMPORTANT:* Just open issues for bugs found on this library.
If you are getting an empty result, please don't open an issue,
it is a usage problem that was already extensively covered on
Gitter <https://gitter.im/thiagoalessio/tesseract-ocr-for-php>.

### Expected behavior

```
echo (new TesseractOCR('test.jpg'))
    ->psm(7)
    ->run();
```

(should output 80975 -- and does using the Tesseract CLI)

### Actual behavior

> read_params_file: Can't open 7
> Warning. Invalid resolution 0 dpi. Using 70 instead.
> Estimating resolution as 172
> Empty page!!
> Estimating resolution as 172
> Empty page!!

#### Environment
```

root@DESKTOP-HFQNGG7:/home/teamcoltra/chinapost# uname -srvm
Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64
root@DESKTOP-HFQNGG7:/home/teamcoltra/chinapost# php --version
PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.28-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
root@DESKTOP-HFQNGG7:/home/teamcoltra/chinapost# tesseract --version
tesseract 4.0.0-beta.1
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0

 Found AVX2
 Found AVX
 Found SSE
root@DESKTOP-HFQNGG7:/home/teamcoltra/chinapost# composer show thiagoalessio/tesseract_ocr
Do not run Composer as root/super user! See https://getcomposer.org/root for details
name     : thiagoalessio/tesseract_ocr
descrip. : A wrapper to work with Tesseract OCR inside PHP.
keywords : OCR, Tesseract, text recognition
versions : * 2.2.2
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/thiagoalessio/tesseract-ocr-for-php.git ebd243ecc65d5d06d88113cd81df0f1cda19d2dc
dist     : [zip] https://api.github.com/repos/thiagoalessio/tesseract-ocr-for-php/zipball/ebd243ecc65d5d06d88113cd81df0f1cda19d2dc ebd243ecc65d5d06d88113cd81df0f1cda19d2dc
names    : thiagoalessio/tesseract_ocr

autoload
psr-4
thiagoalessio\TesseractOCR\ => src/

requires
php ^5.6 || ^7.0

requires (dev)
codacy/coverage dev-master
phpunit/php-code-coverage ^4.0.8
```

**Comment by thiagoalessio** [comment]
Hello @teamcoltra , thanks for reporting it.

Looks like the generated command is not placing the arguments properly, putting the `7` (psm arg) as if it was an image source.

I'll dig into that, but on the mean time, could you please run the following command and share the output here:

    echo (new TesseractOCR('test.jpg'))
        ->psm(7)
        ->buildCommand();

**Comment by thiagoalessio** [comment]
@teamcoltra I've addressed issues regarding incompatibilities between versions 3 and 4 of tesseract on version `2.3.0`. Please let me know if this new release solves your issue.

**Comment by thiagoalessio** [comment]
@teamcoltra ping

**Comment by thiagoalessio** [comment]
maybe you are on vacation but this open issue here is annoying me a bit.
So I'll close it, but if you are still having a problem, please feel free to reopen it.

**Comment by teamcoltra** [comment]
OH! Sorry I am really really awful about checking notifications! The update solved it!

**Comment by SridharClover** [comment]
I am using tesseract 4.0.0-beta.1 version
But still I got 

Tesseract Open Source OCR Engine v4.0.0-beta.1 with Leptonica
Empty page!!
Empty page!!

while I executed on my terminal by this command 
$ tesseract sign.png out

Please any help..
