### ISSUE TITLE
ocr return nothing

### ISSUE THREAD

**Issue by killermouse** [thiagoalessio/tesseract-ocr-for-php#128]
Hi.

I have a problem. I tried to use this wrapper to work with Tesseract OCR inside PHP. But returns nothing!

System: 
Ubuntu 18.04
Xampp
Tesseract version 4.0.0-beta.1

In command line I can execute de tesseract and I get the text from image
`tesseract text.jpeg stdout` 

But in php, the code does not return the text or errors! 

`include_once("vendor/autoload.php");
`
`use thiagoalessio\TesseractOCR\TesseractOCR;`

`$file ='text.jpeg';`

`$ocr = new TesseractOCR($file);`

```
print "<pre>"; 
print_r ($ocr);
print "</pre>";

```

print_r returns:
`
thiagoalessio\TesseractOCR\TesseractOCR Object
(
    [command] => thiagoalessio\TesseractOCR\Command Object
        (
            [executable] => tesseract
            [options] => Array
                (
                )
            [configFile] => 
            [threadLimit] => 
            [image:thiagoalessio\TesseractOCR\Command:private] => text.jpeg
        )
)
`

What is missing!

Best regards

**Comment by thiagoalessio** [comment]
you are just creating a new instance but is not executing the `->run()` method.
Please check the basic usage on the docs: https://github.com/thiagoalessio/tesseract-ocr-for-php#basic-usage

**Comment by thiagoalessio** [comment]
If you have further doubts about the usage, please post them on the project's Gitter:
https://gitter.im/thiagoalessio/tesseract-ocr-for-php
(GitHub issues are meant for bugs or missing features on the library itself)
