### ISSUE TITLE
Return Nothing in PHP 7

### ISSUE THREAD

**Issue by darkterminal** [thiagoalessio/tesseract-ocr-for-php#129]
### Expected behavior

Add relevant code snippet, and what you expect it to do.

### Actual behavior

**EMPTY / NOTHING**

### Steps to reproduce the behavior

Add the tesseract command generated by the library, example:

	<?php
	use thiagoalessio\TesseractOCR\TesseractOCR;
        $file = 'tmp/buktitransferbni.jpg';
        echo (new TesseractOCR($file))->run();

Also, if possible, attach the image(s) you are trying to recognize.

#### Environment

* Operating system: `$ uname -srvm` or `> winver`

  `Linux 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64`

* PHP version: `$ php --version`

  ```bash
  PHP 7.1.13 (cli) (built: Jan 16 2018 14:26:08) ( NTS )
  Copyright (c) 1997-2017 The PHP Group
  Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
  ```

* Tesseract version: `$ tesseract --version`

  ```bash
  tesseract 3.04.01
  leptonica-1.73 libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : 
  libwebp 0.4.4 : libopenjp2 2.1.0
  ```

* tesseract-ocr-for-php version: `$ composer show thiagoalessio/tesseract_ocr`

  ```bash
  name     : thiagoalessio/tesseract_ocr
  descrip. : A wrapper to work with Tesseract OCR inside PHP.
  keywords : OCR, Tesseract, text recognition
  versions : * 2.4.0
  type     : library
  license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText  
  source   : [git] https://github.com/thiagoalessio/tesseract-ocr-for-php.git 
  a8b7a9ba7919e683b9915668f3d0d67ebba6d266
  dist     : [zip] https://api.github.com/repos/thiagoalessio/tesseract-ocr-for- 
  php/zipball/a8b7a9ba7919e683b9915668f3d0d67ebba6d266 
  a8b7a9ba7919e683b9915668f3d0d67ebba6d266
  names    : thiagoalessio/tesseract_ocr

  autoload
  psr-4
  thiagoalessio\TesseractOCR\ => src/

  requires
  php ^5.6 || ^7.0

  requires (dev)
  codacy/coverage dev-master
  phpunit/php-code-coverage ^4.0.8
  ```

**Comment by thiagoalessio** [comment]
Hello @darkterminal, if you get the generated command and manually run it on the command line, what do you get?
```
<?php
use thiagoalessio\TesseractOCR\TesseractOCR;
    $file = 'tmp/buktitransferbni.jpg';
    echo (new TesseractOCR($file))->command;
```

**Comment by darkterminal** [comment]
Hi, @thiagoalessio  if i run in command line it's working, but i expect to return value in browser. How can i did it?

Thanks for advance,
Regards.

**Comment by thiagoalessio** [comment]
hum, something similar just happened yesterday with another user on Gitter. I suggest we close this issue and go there where I could support you. If it turns out that it is actually a bug in the library, then we reopen this one, ok?

waiting you there: https://gitter.im/thiagoalessio/tesseract-ocr-for-php
