### ISSUE TITLE
Returns empty string.

### ISSUE THREAD

**Issue by MuhammadRahman-awin** [thiagoalessio/tesseract-ocr-for-php#13]
Hi,

I am using Centos 5 with tesseract-2.04-2.

When I use tesseract on console I can only read .tif image, for other it does not recognise the type.

But in my script it does not even read the tif, juste return empty string.

This is how I am using it. 

`include('TesseractOCR.php');`
`if (isset($_FILES['file'])) {`
`$tesseract = new TesseractOCR($_FILES['file']['tmp_name']);`
`$result = $tesseract->recognize();`
`}`

Any idea where I am going wrong with it.

**Comment by thiagoalessio** [comment]
tons of things could be wrong, permissions to temp folders, format of the image, etc etc ..
