### ISSUE TITLE
Error with laravel 5.6: Undefined offset 0 on line 59 

### ISSUE THREAD

**Issue by ephraimlambarte** [thiagoalessio/tesseract-ocr-for-php#134]
### Expected behavior
i expect it to return the text in the image

### Actual behavior
i get an error in starting the server

### Steps to reproduce the behavior
1.) put the tesseractOCR class on config/app.php: like this on line 170 and line 194: https://pastebin.com/WS3jah3P 

2.) use TesseractOCR in web.php under routes folder: 

use TesseractOCR;
Route::get('/', function () {
     return (new TesseractOCR(public_path('\text.png')))
     ->run();
});

#### Environment

* Operating system: windows 7
* PHP version: 7.2.6
* capture2text: 3.9
* tesseract-ocr-for-php version: 2.5

**Comment by thiagoalessio** [comment]
@ephraimlambarte i'm just releasing version `2.6.0`, and I expect it to solve your issue. Please let me know if it works, otherwise feel free to re-open this issue ;D

**Comment by ephraimlambarte** [comment]
Hello now im getting different error whenever i start my laravel server that says:

In FriendlyErrors.php line 11:
       file_exists() expects parameter 1 to be a valid path, object given

note: this also happens when i include the tesseract wrapper at config/app.php

**Comment by ephraimlambarte** [comment]
I tried putting this at the start of static function in FriendlyErrors class as a quick fix:
`
if(is_object($image)){
	$image = "C:\\xampp\\htdocs\\laravelprojects\\ocrtest21\\public\\text.png";
}
`
But it produced another error that says:
In ProviderRepository.php line 151:
        Illegal offset type

**Comment by thiagoalessio** [comment]
Hello @ephraimlambarte thanks for the feedback. `ProviderRepository` is not something from my library, I believe it is coming from Laravel.

It seems that something on the framework is trying to create a new instance of `TesseractOCR`  _before_ you actually start using it.

I haven't thought about this kind of usage until now, but I'll do something similar to your quick fix and let you know.

**Comment by thiagoalessio** [comment]
@ephraimlambarte let's try again 😝 please update to `2.6.1` and let me know

**Comment by thiagoalessio** [comment]
@ephraimlambarte any success with the new version?

**Comment by ephraimlambarte** [comment]
Thanks! I'll wait for your update

**Comment by ephraimlambarte** [comment]
its now working. thanks!

**Comment by ephraimlambarte** [comment]
Sorry for the late reply. i will update you today if there are any errors

**Comment by ephraimlambarte** [comment]
i just updated to version 2.6.2 and i got an error saying:
In TesseractOCR.php line 14:

  Object of class Illuminate\Foundation\Application could not be converted to string

**Comment by thiagoalessio** [comment]
@ephraimlambarte i took some time to show this issue to colleagues, and it seems that is only a usage problem, rather than something wrong with the library.

So I'm closing this issue and re-posting this problem on Gitter, is very likely that someone there uses Laravel and might be able to help.

**Comment by thiagoalessio** [comment]
Hello @topherseance , thank you very much for sharing this info here, will certainly be useful for other users!

**Comment by thiagoalessio** [comment]
Hello @topherseance , thank you very much for sharing this info here, will certainly be useful to other users!
