### ISSUE TITLE
Error with PHP 5.4 and composer.

### ISSUE THREAD

**Issue by paloke** [thiagoalessio/tesseract-ocr-for-php#135]
### Expected behavior

The text of the test.png image

### Actual behavior

After composer update:
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
I get:

A PHP Error was encountered
Severity: Parsing Error
Message: syntax error, unexpected '.', expecting ')'
Filename: src/TesseractOCR.php
Line Number: 49

### Steps to reproduce the behavior

defined('BASEPATH') OR exit('No direct script access allowed');
use thiagoalessio\TesseractOCR\TesseractOCR;
class Ocr extends CI_Controller {
  public function test_ocr(){
  	echo (new TesseractOCR('test.png'))->run();
  }
}

#### Environment

* Operating system: Linux 2.6.32-32-pve #1 SMP Thu Aug 21 08:50:19 CEST 2014 i686
* PHP version: PHP 5.4.45-0+deb7u14 (cli) (built: May  9 2018 18:47:17)
* Tesseract version: tesseract 3.02
* tesseract-ocr-for-php version: 
name     : thiagoalessio/tesseract_ocr
descrip. : A wrapper to work with Tesseract OCR inside PHP.
keywords : OCR, Tesseract, text recognition
versions : * 2.0.0

**Comment by thiagoalessio** [comment]
Hello @paloke I've seen that you are using version `2.0.0` of this library, but back then I was only supporting PHP 5.6+.

I'm currently working on supporting older PHP versions, please experiment with version `2.6.0` or `dev-master` and let me know ;D

**Comment by paloke** [comment]
Hi, 
After doing a `composer update` It works like a charm.

thank you
