### ISSUE TITLE
macos command not found

### ISSUE THREAD

**Issue by a236220500** [thiagoalessio/tesseract-ocr-for-php#137]
class FriendlyErrors

function checkTesseractPresence
Under MacOS, PHP_OS is Darwin, so $cmd is always "where", which leads to "sh: where: command not found"; looks forward to repair.

**Comment by thiagoalessio** [comment]
Ohhh good catch! Can you believe I developed this on a mac? But I only ran tests inside a linux container.

Thank you very much for reporting this one, will fix it tonight.

**Comment by thiagoalessio** [comment]
@a236220500 Thanks again, already pushed a fix and I'm bumping the version (to `2.6.2`) so that you can already make use of it.
