### ISSUE TITLE
Not loading Tesseract OCR in Windows

### ISSUE THREAD

**Issue by Deparagon** [thiagoalessio/tesseract-ocr-for-php#138]
Tesseract OCR is properly installed, i can use tesseract using "exec" command

Also when i run "Which tesseract" on command prompt 
I get "/c/ProgramData/chocolatey/bin/tesseract"

Using this package 
require_once dirname(__FILE__).'/vendor/autoload.php';
use thiagoalessio\TesseractOCR\TesseractOCR;
echo (new TesseractOCR('n.jpg'))
    ->run();
I get the message below
The command "tesseract" was not found. Make sure you have Tesseract OCR installed on your system

Any idea why it's so...

**Comment by thiagoalessio** [comment]
Hello, in order for me to have a better understanding on your env and how to potentially reproduce your problem, I kindly ask you to fill the details requested on the issue template: https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by Deparagon** [comment]
**I expect a image to text conversion of the image n.jpg** 
 **Code:**
`require_once dirname(__FILE__).'/vendor/autoload.php';
use thiagoalessio\TesseractOCR\TesseractOCR;
echo (new TesseractOCR('n.jpg'))
    ->run();`

Actual behavior
The command "tesseract" was not found. Make sure you have Tesseract OCR installed on your system

**Steps to reproduce the behavior**

```
require_once dirname(__FILE__).'/vendor/autoload.php';
use thiagoalessio\TesseractOCR\TesseractOCR;
echo (new TesseractOCR('n.jpg'))
    ->run();
```





**Environment** 

**Opterating system**: Windows 10 version 1803 (OS Build 17134.112)

**PHP version:** PHP 7.2.2 (cli) (built: Jan 31 2018 19:51:55) ( ZTS MSVC15 (Visual C++ 2017) x86 )
**Tesseract version**: tesseract 3.05.00dev


**$ composer show thiagoalessio/tesseract_ocr**

```
name     : thiagoalessio/tesseract_ocr
descrip. : A wrapper to work with Tesseract OCR inside PHP.
keywords : OCR, Tesseract, text recognition
versions : * 2.6.1
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/thiagoalessio/tesseract-ocr-for-php.git d324a59b5e3892012f18fb7dd514ce6fb3733cb9
dist     : [zip] https://api.github.com/repos/thiagoalessio/tesseract-ocr-for-php/zipball/d324a59b5e3892012f18fb7dd514ce6fb3733cb9 d324a59b5e3892012f18fb7dd514ce6fb3733cb9
names    : thiagoalessio/tesseract_ocr

autoload
psr-4
thiagoalessio\TesseractOCR\ => src/

```

**Comment by Deparagon** [comment]
Glad you are attending to it..
Great Thanks...

**Comment by thiagoalessio** [comment]
Hello @Deparagon ,

Sorry it took so long, but turned out that was a very stupid mistake from my side ... I already provided a fix and released on version `2.6.3`. Please let me know if it was enough to solve your problem, otherwise feel free to reopen this issue anytime ;D

**Comment by Deparagon** [comment]
This is great. Thanks for the update.

**Comment by tahakaanyilmaz** [comment]
I have the same problem. I applying same steps but I have already this problem. Help me.
