### ISSUE TITLE
Running tesseract results in an empty string when filename starts with $

### ISSUE THREAD

**Issue by nonetallt** [thiagoalessio/tesseract-ocr-for-php#139]
### Expected behavior

$filepath = Storage::disk('cards')->getAdapter()->applyPathPrefix('$293.png');
$ocr = new TesseractOCR($filepath);
$result = $ocr->run();
dd($result);

// text from the image

### Actual behavior

// an empty string is diplayed

### Steps to reproduce the behavior

1. Find any file that you can get a successful text detection out of.
2. Rename that file so it starts with $.
3. Try text detection for the renamed file.

### EDIT1

The same problem seems to occur when there is a $ character in any part of the filename.

#### Environment

* Operating system: Linux 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64
* PHP version: PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )
* Tesseract version: tesseract 3.04.01
* tesseract-ocr-for-php version: 2.4

**Comment by thiagoalessio** [comment]
Hello @nonetallt
Thanks for reporting it. I will provide a fix tonight and let you know ;D

**Comment by thiagoalessio** [comment]
Hello again @nonetallt the fix is already present on release `2.6.3`. Please update and check if it was enough to solve your problem. If not, feel free to reopen this issue anytime ;D
