### ISSUE TITLE
use this lib on shared host

### ISSUE THREAD

**Issue by naweed1998** [thiagoalessio/tesseract-ocr-for-php#140]
hi 
i want to use this on shared host .
i downloaded it and upload on my host
i use this code

`<?php`
`REQUIRE_ONCE __DIR__."/src/TesseractOCR.php";`
`echo (new TesseractOCR("images.jpg"))->run();`

but i got this error_log:

`PHP Fatal error:  Uncaught Error: Class 'TesseractOCR' not found`
what is the problem???

**Comment by thiagoalessio** [comment]
Please use the appropriate channels to get help: https://github.com/thiagoalessio/tesseract-ocr-for-php#where-to-get-help
Issues are meant to report bugs found on the library.
