### ISSUE TITLE
Image Without text

### ISSUE THREAD

**Issue by Dlohani1** [thiagoalessio/tesseract-ocr-for-php#141]
If we check for an image without text then it throws error like output cannot be generated.

**Comment by thiagoalessio** [comment]
hi there! well, it makes sense ... what were you expecting it would return? empty string without throwing exceptions?

**Comment by Dlohani1** [comment]
look, I don't know whether the image contains text or not. If the image does not contain any text then the temporary text file length will be 0 from where you are throwing the exception. How I can catch that exception to continue my script execution.

**Comment by thiagoalessio** [comment]
Using a [try/catch](http://php.net/manual/en/language.exceptions.php) ?
if you want plz post a code snippet so i can have a better understanding of what you are trying to achieve.

**Comment by Dlohani1** [comment]
public static function checkCommandExecution($command, $stdout)
	{
		$file = "{$command->getOutputFile()}.txt";
		if (file_exists($file) && filesize($file) > 0) return;
		$msg = array();
		$msg[] = 'Error! The command did not produce any output.';
		$msg[] = '';
		$msg[] = 'Generated command:';
		$msg[] = "$command";
		$msg[] = '';
		$msg[] = 'Returned message:';
		$msg = array_merge($msg, $stdout);
		$msg = join(PHP_EOL, $msg);
		throw new UnsuccessfulCommandException($msg);
	}

How to catch this error 'throw new UnsuccessfulCommandException($msg);' ?

my code : 
<?php 
$path = "image-path";
echo (new TesseractOCR($path))->run();
?>

It returns the text if present in the image. 
When Image is without any text it returns the following error : 
  "message": "Error! The command did not produce any output.\n\nGenerated command:\n\"tesseract\" \"/tmp/phpRdQBe5\" /tmp/ocrw74oup\n\nReturned message:\nTesseract Open Source OCR Engine v3.04.01 with Leptonica",

**Comment by thiagoalessio** [comment]
ok, got you ... so it is definitely an _usage_ problem, nothing wrong with the library itself.
For that reason I'll close this issue and invite you to continue this conversation on the project's [Gitter](https://gitter.im/thiagoalessio/tesseract-ocr-for-php). (already mentioned you in there)

**Comment by Dlohani1** [comment]
Thanks it worked.

Regards
Deepak Lohani
