### ISSUE TITLE
 Operator < bug

### ISSUE THREAD

**Issue by nourhatoum86** [thiagoalessio/tesseract-ocr-for-php#143]
i have issue with the operator character < where it take it as a wrong character such as K or c or e. 
please could you fix it.

**Comment by thiagoalessio** [comment]
Hello @nourhatoum86 

This is outside of the scope of my wrapper, therefore there is nothing I can do to fix it.
The only thing I can think of for you as an attempt to minimise such errors is to create a whitelist (https://github.com/thiagoalessio/tesseract-ocr-for-php#whitelist)
