### ISSUE TITLE
Can not use with url image

### ISSUE THREAD

**Issue by ZhaoSin** [thiagoalessio/tesseract-ocr-for-php#144]
Dear,

I tried 
$vcl = (new TesseractOCR('https://i.imgur.com/wSKs0G5.jpg'))
    ->run();

But result is empty!

**Comment by thiagoalessio** [comment]
Please use the appropriate channels to get help: https://github.com/thiagoalessio/tesseract-ocr-for-php#where-to-get-help
Issues are meant to report bugs found on the library.
