### ISSUE TITLE
hocr not working

### ISSUE THREAD

**Issue by nishantha-kumara** [thiagoalessio/tesseract-ocr-for-php#151]
Hi, I have use tesseract ocr for my personal project and i cant use hocr option. every time getting following error.
but in command line, hocr option working fine.

### Expected behavior

$data['fileText'] = (new TesseractOCR(public_path() . $document->file_path))
            ->configFile('hocr')
            ->run();

### Actual behavior

Error! The command did not produce any output.

Generated command:
"tesseract" "/var/www/html/final-project-cms/public/pics/2018-12-11/0p91544545389.png" /tmp/ocrv8ZIBB hocr

Returned message:
Tesseract Open Source OCR Engine v3.04.01 with Leptonica

#### Environment

* Operating system: `ubuntu 16.04`
* PHP version: `7.2`
* Tesseract version: `tesseract 3.04.01`
* tesseract-ocr-for-php version: `* 2.7.1`

**Comment by thiagoalessio** [comment]
Hello @nishantha-kumara thank you very much for reporting it. I managed to reproduce the bug and will start working on a fix for that.

**Comment by thiagoalessio** [comment]
Hi again @nishantha-kumara please update to version `2.7.2` and let me know if it solves your problem ;D

**Comment by nishantha-kumara** [comment]
good job @thiagoalessio , now its working fine.
Thank you.

**Comment by thiagoalessio** [comment]
Nice!
