### ISSUE TITLE
Allow to set a custom temp folder in TesseractOCR() constructor ?¿

### ISSUE THREAD

**Issue by idevelopthings11** [thiagoalessio/tesseract-ocr-for-php#153]
Using tesseract on CentOS 7. Some shared hostings or server do not have temp folders properly configured so tesseract-for-php fails to create a file on the right tmp folder (php is actually using another folder for tmp)

This line of code on Command.php:

`		$this->outputFile = $outputFile ?: tempnam(sys_get_temp_dir(), 'ocr');
`
sys_get_temp_dir() returns /tmp even when php is configured to use other directory as a tmp folder. 

A parameter to allow to make this path custom from TesseractOCR() would be appreciated.

**Comment by thiagoalessio** [comment]
Hello @idevelopthings11 

After a long time off, I finally managed to have some time to address this bug.
Please let me know if it works for you. (version `2.7.3` https://github.com/thiagoalessio/tesseract-ocr-for-php#tempdir)

**Comment by thiagoalessio** [comment]
closing this issue for now. please feel free to reopen it if the new version didn't solve the problem.
