### ISSUE TITLE
Command not found in macos

### ISSUE THREAD

**Issue by nishantha-kumara** [thiagoalessio/tesseract-ocr-for-php#154]
### Actual behavior

Hi, Im using tesseract ocr and your package for some development part. My programme working fine in linux environment but programme not working in my mac. tesseract command still working on command line interface. but in the programme, still given following error.

`Error! The command "tesseract" was not found. Make sure you have Tesseract OCR installed on your system: https://github.com/tesseract-ocr/tesseract The current $PATH is /usr/bin:/bin:/usr/sbin:/sbin
`
### Steps to reproduce the behavior

Add the tesseract command generated by the library, example:

	<?php
	$data['fileText'] = (new TesseractOCR(public_path() . $document->file_path))
            ->hocr()
            ->psm(4)
            ->run();

#### Environment

* Operating system: `MacOS Mojave`
* PHP version: `7.2 (home brew)`
* Tesseract version: `tesseract 4.0.0`
* tesseract-ocr-for-php version: `"thiagoalessio/tesseract_ocr": "2.7.2",`

**Comment by thiagoalessio** [comment]
Homebrew installs binaries at /usr/local/bin, not present in the PATH you posted.
Closing this since it is not an issue with the library itself, is just a usage problem.

**Comment by nishantha-kumara** [comment]
How can I fix this issue?
