### ISSUE TITLE
How to Use Network Pictures

### ISSUE THREAD

**Issue by Tomorrowxxy** [thiagoalessio/tesseract-ocr-for-php#156]
hi ~
  I encountered problems in using it. I don't know how to use network pictures. 
  for example  echo (new TesseractOCR('https://google.com/xxxxx'))->run();
  Does this project support writing like this?

**Comment by awkwardusername** [comment]
You can just download the image to a temp and process from there.

**Comment by Tomorrowxxy** [comment]
Can you give an code example?

**Comment by awkwardusername** [comment]
you can look at https://secure.php.net/manual/en/function.file-get-contents.php

Make sure to validate the contents of the file before processing it.

**Comment by thiagoalessio** [comment]
@awkwardusername thank you very much for replying the question.
@Tomorrowxxy at the moment that is the only solution, but in a future release I might add the ability to load an image from the network.

**Comment by thiagoalessio** [comment]
organizing past issues, and found that #144 also would like to fetch images from an URL ... feature added to my backlog.

**Comment by Tomorrowxxy** [comment]
Oh, it would be great if you support the use of web pictures.
Waiting for your update.

I am not currently using tesseract-ocr-for-php, because tesseract takes up server resources too much and causes the server to go down. Do you have any optimization methods?
