### ISSUE TITLE
Is userPatterns working?

### ISSUE THREAD

**Issue by KilianSillero** [thiagoalessio/tesseract-ocr-for-php#158]
According to [this ](https://github.com/tesseract-ocr/tesseract/issues/403) issue in tesseract, userPatters does not work.
I have the code as in the example:

`echo (new TesseractOCR('img.png'))
    ->userPatterns('/patterns/patterns.txt')
    ->run();`

And there is no difference with or without the pattern.
I'm doing something wrong or the pattern just doesn't work?

I am using: 
- Tesseract version: 4.0.0_1
- tesseract-ocr-for-php version: 2.7.3

**Comment by thiagoalessio** [comment]
hi @KilianSillero, you are using it correctly ... but if tesseract itself has the issue there is not much else we can do 😔

**Comment by KilianSillero** [comment]
Maybe with  `->oem(0)` I could make it work?
Anyways, thanks for the quick response.
