### ISSUE TITLE
is there a way to scan only first word of a page?

### ISSUE THREAD

**Issue by vkasharma** [thiagoalessio/tesseract-ocr-for-php#159]
Hello guys,

I am trying to identify page category by recognizing the only first word on a page, but the pages can have much more text so it is taking so much time. I just wanted to limit scanning to one word only. I have tried psm option but no luck there.

**Comment by thiagoalessio** [comment]
Hi, please refrain from opening issues with questions ... there is a more appropriate channel for that: https://gitter.im/thiagoalessio/tesseract-ocr-for-php
