### ISSUE TITLE
Tesseract OCR

### ISSUE THREAD

**Issue by elahiammar** [thiagoalessio/tesseract-ocr-for-php#16]
I am bascially a beginner in programming and developing a web application which converts Image into Text i have used Orcad for this but it's for simple text and creating many issues i want to know is this i helpful to me that i can give an interface to user in which he can upload a file of  formats like png, jpeg etc and that web app converts it into text i am bascially learning node.js for this kindly guide me which is better and easy to learn particulary for this project?

**Comment by thiagoalessio** [comment]
closing this chat room ;D
