### ISSUE TITLE
How to find firstname and lastname from german Id passport?

### ISSUE THREAD

**Issue by drcsystems78** [thiagoalessio/tesseract-ocr-for-php#161]
I am trying to read German id (passport) in which I want to get user's information like the first name,  last name, DOB, country, city, street, etc. this information will be used for creating a user so you have any idea to how to recognize user details from German id passport?
I am reading below image:
![idFront](https://user-images.githubusercontent.com/28754925/57906898-37064d00-7899-11e9-9996-451b4c07f157.jpg)
`echo $orcContent = (new TesseractOCR('/var/www/html/OCR/images/my_passport.jpg'))->run();`
here response:
`www.ms.” T22000129 P'l'm‘“ MUSTERMANN GUS. WCK ._..,.___...._ ERIKA gamut-aw W 12.08.1964 DEUTSCH mum...— BERLIN I3:1..10.“2-5.2;'0 938 568 I W1`

So is there any way to find the user's details?

**Comment by thiagoalessio** [comment]
Please use the appropriate channels to get help: https://github.com/thiagoalessio/tesseract-ocr-for-php#where-to-get-help
Issues are meant to report bugs found on the library.
