### ISSUE TITLE
Digits() or Whitelist() doesn't work

### ISSUE THREAD

**Issue by renziito** [thiagoalessio/tesseract-ocr-for-php#162]
### Expected behavior

Filter by digits or whitelist

### Actual behavior

No filter at all.

### Steps to reproduce the behavior

	<?php
	use thiagoalessio\TesseractOCR\TesseractOCR;
	echo (new TesseractOCR('digits.png'))->digits()->run;

or

	<?php
	use thiagoalessio\TesseractOCR\TesseractOCR;
	echo (new TesseractOCR('digits.png'))->whitelist(range(0, 9)->run;

#### Environment

* Operating system: Windows 10
 PHP version: 7.1.29
* Tesseract version: v4.0.0.20190314
* tesseract-ocr-for-php version: * 2.7.3

**Comment by thiagoalessio** [comment]
Hi @renziito , would you mind sharing the image you are using? (`digits.png`)

**Comment by thiagoalessio** [comment]
Hi @renziito, apparently Tesseract 4 doesn't support blacklist/whitelist yet: https://github.com/tesseract-ocr/tesseract/issues/751
