### ISSUE TITLE
Does it work on a hosting?

### ISSUE THREAD

**Issue by Marko97IT** [thiagoalessio/tesseract-ocr-for-php#165]
This is created with PHP. I need to use this software only with Apache without installing any other software on the O.S. for example for a hosting. It is possible?

**Comment by thiagoalessio** [comment]
Let's keep issues only for bugs found on this library.
For questions, I'd like to invite you over to https://gitter.im/thiagoalessio/tesseract-ocr-for-php where we can chat about what you are trying to accomplish.
