### ISSUE TITLE
This XML file does not appear

### ISSUE THREAD

**Issue by karunasri-acs** [thiagoalessio/tesseract-ocr-for-php#166]
hii 
i cloned the project to my htdocs and trying to run the application in my localhost but i am getting 
This XML file does not appear to have any style information associated with it. The document tree is shown below. in /tesseract/phpcs.xml 
can you please help to run the application in my local
![Screenshot (308)](https://user-images.githubusercontent.com/52414276/61746755-03c0cc80-adba-11e9-9d8d-b2af2a7d17bf.png)

**Comment by thiagoalessio** [comment]
Please use the appropriate channels to get help: https://github.com/thiagoalessio/tesseract-ocr-for-php#where-to-get-help
Issues are meant to report bugs found on the library.
