### ISSUE TITLE
ERROR Unsuccessful CommandException

### ISSUE THREAD

**Issue by oscar033** [thiagoalessio/tesseract-ocr-for-php#167]
I have the following message: thiago alessio \ Tesseract OCR \ Unsuccessful CommandException
and I do not understand why. Anyone would have the solution? my code is the following:
use thiagoalessio \ TesseractOCR \ TesseractOCR;
    $ app-> get ('/ OCR /', function ($ request, $ response, $ args) {
        $ filename = '../vendor/thiagoalessio/tesseract_ocr/src/text.png';
if (file_exists ($ filename)) {
$ result = true;
require ( "../ vendor / thiagoalessio / tesseract_ocr / src / TesseractOCR.php");
require ( "../ vendor / thiagoalessio / tesseract_ocr / src / Option.php");
require ( "../ vendor / thiagoalessio / tesseract_ocr / src / FriendlyErrors.php");
require ( "../ vendor / thiagoalessio / tesseract_ocr / src / command.php");
$ ocr = (new TesseractOCR ());
// $ ocr -> executable ('../ vendor / thiagoalessio / tesseract_ocr / src');
$ ocr -> image ($ filename);
$ result = $ ocr -> run ();
thank you

**Comment by thiagoalessio** [comment]
Please use the appropriate channels to get help: https://github.com/thiagoalessio/tesseract-ocr-for-php#where-to-get-help
Issues are meant to report bugs found on the library.
