### ISSUE TITLE
temporary files not deleted

### ISSUE THREAD

**Issue by momala454** [thiagoalessio/tesseract-ocr-for-php#169]
the remporary files created by

public function getOutputFile($withExt=true)
	{
		>>>>>>>>if (!$this->outputFile) $this->outputFile = tempnam($this->getTempDir(), 'ocr');
		if (!$withExt) return $this->outputFile;
		$hasCustomExt = ['hocr', 'tsv', 'pdf'];
		$ext = in_array($this->configFile, $hasCustomExt) ? $this->configFile : 'txt';
		return "{$this->outputFile}.{$ext}";
	}

are never deleted. It create 2 files, one ocrXXX and one ocrXXX.txt

**Comment by momala454** [comment]
workaround:

$todelete = $ocr->command->getOutputFile();
$todelete2 = preg_replace('/\.txt$/', '', $todelete);
if (!empty($todelete) && is_file($todelete)) unlink($todelete);
if (!empty($todelete2) && is_file($todelete2)) unlink($todelete2);

**Comment by thiagoalessio** [comment]
Oh, just managed to reproduce it ... thanks for reporting, I'll start working on a fix for that and let you know once its done ;D

**Comment by momala454** [comment]
it is dangerous to use * to delete files, and getOutputFile() returned the file with .txt at the end, while it also created a temporary file without .txt

**Comment by momala454** [comment]
please use a better solution and try to delete only files using the exact name and not *

**Comment by thiagoalessio** [comment]
> it is dangerous to use * to delete files,

I don't use `*` to delete them, that's the input for `glob`

**Comment by momala454** [comment]
yes but glob will return all files matching, so if it matches files not related they will be deleted too

**Comment by momala454** [comment]
why not delete only files
getOutputFile()
and
getOutputFile(true)

**Comment by thiagoalessio** [comment]
hm, yes ... i liked that idea!

**Comment by thiagoalessio** [comment]
Done, available in version `2.7.6`. Again, thank you so much for reporting it and for reviewing and refining my original solution. Great stuff !!!
:heart: :yellow_heart: :green_heart: :blue_heart: :purple_heart: :black_heart:
