### ISSUE TITLE
PDF files

### ISSUE THREAD

**Issue by vitormicillo** [thiagoalessio/tesseract-ocr-for-php#174]
Hello, this is not a bug or problem, just a question.
Is it possible for the library to read PDF files and not just images?

And thank you so much for your library, it helps me a lot

**Comment by rodrigocalilo** [comment]
Yoy may use https://github.com/spatie/pdf-to-text to extract text in pdf files.

**Comment by vitormicillo** [comment]
> The package not suport pdf files.
> You may use https://github.com/spatie/pdf-to-text to extract text in pdf files.

It doesn't work, because inside the PDF the content is converted into images.

**Comment by thiagoalessio** [comment]
I talked to @vitormicillo over email, suggested him to convert it to `tiff` ... please let us know how it turned out ;D

**Comment by vitormicillo** [comment]
Yes @thiagoalessio spoke to me.
I'm converting the PDF files to PNG before reading.

**Comment by muzjsr** [comment]
Ah sorry, i misinterpreted the issue.
You are absolutely right. It is not possible to **INPUT** an pdf-file.
Converting is the only option. I have good results with converting to `*.tiff`.

With my merge request it is possible to get an pdf-file as **OUTPUT**.
The recognized Text is placed behind the picture, so it is searchable and you can select and copy from the document.

**Comment by vitormicillo** [comment]
@muzjsr TIFF format is really big, you can use PNG with this parameter to convert:
convert file.pdf -density 300 file.png

**Comment by muzjsr** [comment]
@vitormicillo 
I am using this parameters for convert:
 `-density 300 -white-threshold 90% -black-threshold 10% -alpha off  -strip -background white`
Output format is TIFF.
Size is not a problem for me, but speed is.
So i will give it a try with png when i have time for a comparison.

**Comment by muzjsr** [comment]
So my results:
With PNG: 
- Recognition results are worse (in my two test files)
- takes ~10% longer

As Tesseract is using Tiff internally my guess is:
If you are using png tesseract will convert it to tiff anyway. so it takes longer.
And because png isnt lossless you are loosing information as well.

My conclusion is:
I stay with TIFF.

Greetings
Johannes

**Comment by vitormicillo** [comment]
Good to know,
What command do you use for tesseract to read PDF files and convert them to
images tiff?
or are you converting before reading?
