### ISSUE TITLE
is there a way to set the return type from text to json with lables like google cloud vision ?

### ISSUE THREAD

**Issue by accidentul** [thiagoalessio/tesseract-ocr-for-php#176]
Sorry for the issue but .... is there a way to set the return type from text to json/array with lables like google cloud vision ?

**Comment by thiagoalessio** [comment]
Please use the appropriate channels to get help: https://github.com/thiagoalessio/tesseract-ocr-for-php#where-to-get-help
Issues are meant to report bugs found on the library.
