### ISSUE TITLE
How to use regular expressions with tesseract-php

### ISSUE THREAD

**Issue by shashika89** [thiagoalessio/tesseract-ocr-for-php#18]
I m running tesseract on windows (xampp), I want to format the result what I want, It should be in  \d{1,9}.((v|V)|(x|X))  format.  Can someone help me how to setup that rule in tesseract in php.

**Comment by thiagoalessio** [comment]
to enforce only digits, you can use ranges, check "inducing recognition" on the readme

    $tesseract->setWhitelist(range(0,9));

and just check if the result length is between 1 and 9 after.
