### ISSUE TITLE
How can i setup path on Cpanel ?

### ISSUE THREAD

**Issue by dhiman11** [thiagoalessio/tesseract-ocr-for-php#181]
I am able to execute the results . Thats good

Now i want to move the files to cpanel . I am wondering that how to setup $PATH in cpanel 

Please help .

**Comment by thiagoalessio** [comment]
Please don't use issues for questions ... issues are meant to report bugs or request features on the library. [Gitter](https://gitter.im/thiagoalessio/tesseract-ocr-for-php) is the right place for usage questions.
