### ISSUE TITLE
Captcha not solved

### ISSUE THREAD

**Issue by BizioM** [thiagoalessio/tesseract-ocr-for-php#188]
![captcha](https://user-images.githubusercontent.com/41058956/93464210-1add4a80-f8e9-11ea-8413-14312c72d7c4.jpg)

Hello and thx for the good job.

My issue is that the captcha is solved i every 10 times. All captcha look like the one attached, so nothing really complicated.

Do you have any solution?

PS the response of your script to the attached one is EXVRMN

Ps 2: when i want to use the whitelist, that does not work. As example if i add ->whitelist(range('0', '9')) the response is always only letters

**Comment by thiagoalessio** [comment]
that's an usage problem, not an issue with the library itself; So I'll close this GH issue and invite you to seek advice from our [user group in Gitter](https://gitter.im/thiagoalessio/tesseract-ocr-for-php), which is the appropriate place for questions like yours.

**Comment by BizioM** [comment]
Im Sorry but the whitelist yes i guess. Why it doesn't work?
