### ISSUE TITLE
No issues just question

### ISSUE THREAD

**Issue by ezalorsara** [thiagoalessio/tesseract-ocr-for-php#19]
I want to use bufferimage or image raw data as input in tesseract. 
let's say i have a big image and I want only a small portion of it, to read by tesseract.
I can do Imagemagick crop method, the problem is 
new TesseractOCR() // only accept only existing file not raw data. 
that means I need to use Imagemagick->writeImage() method. to create local file // which is not efficient.
Does anyone know how to do it.  directly input image data in tesseract. Thanks.

<?php 

require './TesseractOCR.php';
$file = $_SERVER['DOCUMENT_ROOT'] . 'testocr/sample.png';
$img = new Imagick($file);
$img->cropImage(100,100,0,0);
$a =  new TesseractOCR($img); // I want tesseract to accept image directly without writing it. 
echo $a->recognize();

?>

**Comment by winkelement** [comment]
I think the only way to do that would be to output the result from convert to stdout and let tesseract read from stdin. Imagemagick convert writing to stdout is no problem but stdin for tesseract actually is.
See here:
https://code.google.com/p/tesseract-ocr/issues/detail?id=813
https://code.google.com/p/leptonica/issues/detail?id=77

Anyway i don't see a problem with writing and reading from disk as this should be the fastest operation in the whole ocr process compared to image processing with imagemagick and the character recognition with tesseract.

**Comment by ezalorsara** [comment]
Thanks winkelement.
I'm writing a automatic form processing it will auto fill up the html form. base on the data from the form image, you'll see I'm doing a bunch of writeImage. I think it is much faster if I can input the image raw data. that way I will not need to use writeImage that makes a image file.
function read_form(){

		//load tesseract
		require APPPATH . 'libraries' . '/' . 'TesseractOCR.php';

		$form_name = strip_tags($_POST['fileName']);
	
		$data = array();

		$root = $_SERVER['DOCUMENT_ROOT'];
		$app_dir = rtrim($root, 'public') . 'application';
		$form_dir = $app_dir . '/form_images/' . $this->session->userdata('id') . '/';
		$file = $form_dir. $form_name; 

		if(file_exists($file) == TRUE){

			$srn = new Imagick($file);
			$srn->cropImage(704, 78, 204,  630);
			$srn->writeImage($form_dir . 'srn.png');
			$srn_obj = new TesseractOCR($form_dir . 'srn.png');
			$srn_val = $srn_obj->recognize();
			
			$fname = new Imagick($file);
			$fname->cropImage(476, 90, 204, 1050);
			$fname->writeImage($form_dir . 'fname.png');
			$fname_obj = new TesseractOCR($form_dir . 'fname.png');
			$fname_val = $fname_obj->recognize();

			$mname = new Imagick($file);
			$mname->cropImage(476, 90, 750, 1050);
			$mname->writeImage($form_dir . 'mname.png');
			$mname_obj = new TesseractOCR($form_dir . 'mname.png');
			$mname_val = $mname_obj->recognize();

			$lname = new Imagick($file);
			$lname->cropImage(474, 90, 1294, 1050);
			$lname->writeImage($form_dir . 'lname.png');
			$lname_obj = new TesseractOCR($form_dir . 'lname.png');
			$lname_val = $lname_obj->recognize();

			$month = new Imagick($file);
			$month->cropImage(314, 93,204,1492);
			$month->writeImage($form_dir . 'month.png');
			$month_obj = new TesseractOCR($form_dir . 'month.png');
			$month_val = $month_obj->recognize();

			$day = new Imagick($file);
			$day->cropImage(194,93,598,1492);
			$day->writeImage($form_dir . 'day.png');
			$day_obj = new TesseractOCR($form_dir . 'day.png');
			$day_val = $day_obj->recognize();

			$year = new Imagick($file);
			$year->cropImage(242, 93, 878, 1492);
			$year->writeImage($form_dir . 'year.png');
			$year_obj = new TesseractOCR($form_dir . 'year.png');
			$year_val = $year_obj->recognize();

			$tel = new Imagick($file);
			$tel->cropImage(552,95, 204, 1936);
			$tel->writeImage($form_dir . 'tel.png');
			$tel_obj = new TesseractOCR($form_dir . 'tel.png');
			$tel_val = $tel_obj->recognize();

			$mobile = new Imagick($file);
			$mobile->cropImage(510,95,868,1936);
			$mobile->writeImage($form_dir . 'mobile.png');
			$mobile_obj = new TesseractOCR($form_dir . 'mobile.png');
			$mobile_val = $mobile_obj->recognize();

			$email = new Imagick($file);
			$email->cropImage(608, 95,1482, 1936);
			$email->writeImage($form_dir . 'email.png');
			$email_obj = new TesseractOCR($form_dir . 'email.png');
			$email_val = $email_obj->recognize();

			$address = new Imagick($file);
			$address->cropImage(2144, 88, 204,2460);
			$address->writeImage($form_dir . 'address.png');
			$address_obj = new TesseractOCR($form_dir . 'address.png');
			$address_val = $address_obj->recognize();
			
			$province = new Imagick($file);
			$province->cropImage(472, 90, 204,2698);
			$province->writeImage($form_dir . 'province.png');
			$province_obj = new TesseractOCR($form_dir . 'province.png');
			$province_val = $province_obj->recognize();

			$city = new Imagick($file);
			$city->cropImage(470, 90, 750, 2698);
			$city->writeImage($form_dir . 'city.png');
			$city_obj = new TesseractOCR($form_dir . 'city.png');
			$city_val = $city_obj->recognize();

			$brgy = new Imagick($file);
			$brgy->cropImage(472, 90, 1295, 2698);
			$brgy->writeImage($form_dir . 'brgy.png');
			$brgy_obj = new TesseractOCR($form_dir . 'brgy.png');
			$brgy_val = $brgy_obj->recognize();

			$zip = new Imagick($file);
			$zip->cropImage(472, 90, 1840, 2698);
			$zip->writeImage($form_dir . 'zip.png');
			$zip_obj = new TesseractOCR($form_dir . 'zip.png');
			$zip_val = $zip_obj->recognize();

			$id_type = new Imagick($file);
			$id_type->cropImage(530, 92, 204, 3082);
			$id_type->writeImage($form_dir . 'id_type.png');
			$id_type_obj = new TesseractOCR($form_dir . 'id_type.png');
			$id_type_val = $id_type_obj->recognize();

			$id_no = new Imagick($file);
			$id_no->cropImage(572, 92, 808, 3082);
			$id_no->writeImage($form_dir . 'id_no.png');
			$id_no_obj = new TesseractOCR($form_dir . 'srn.png');
			$id_no_val = $id_no_obj->recognize();
			$data = array(
			'srn' => $srn_val,
			'fname' => $fname_val,
			'mname' => $mname_val,
			'lname' => $lname_val,
			'month' => $month_val,
			'day' => $day_val,
			'year' => $year_val,
			'tel' => $tel_val,
			'mobile' => $mobile_val,
			'email' => $email_val,
			'address' => $address_val,
			'province' => $province_val,
			'barangay' => $brgy_val,
			'city' => $city_val,
			'zip' => $zip_val,
			'id_type' => $id_type_val,
			'id_no' => $id_no_val,
			'msg' => 'read successful!'
			);
		}else{
			$data = array(
				'msg' => 'File not exist!'
				);
		}

		
		echo json_encode($data);
	}
