### ISSUE TITLE
Error! The command did not produce any output | for image with no text

### ISSUE THREAD

**Issue by bazzacad** [thiagoalessio/tesseract-ocr-for-php#191]
### Expected behavior
When someone upload an image with no text, I get the error below. I expected the Try/Catch to work, but the code never gets to the catch. I get the PHP error on the  ->Run(); line.

```
use thiagoalessio\TesseractOCR\TesseractOCR;

try {
    $searchkeywords = (new TesseractOCR($mypath2))
        ->whitelist(range('0', '9'))
        ->run();
}

catch (Exception $e) {
    $err = $e->getMessage();
    error_log("OCR Error");
    exit();
}
```

### Actual behavior
`PHP Fatal error:  Uncaught thiagoalessio\\TesseractOCR\\UnsuccessfulCommandException: Error! The command did not produce any output.\n\nGenerated command:\n"tesseract" "/var/www/html/barry_devel/office-db/temp/cropInvoice.png" "/tmp/ocrzsQgJX" -c "tessedit_char_whitelist=0123456789"\n\nReturned message:\nTesseract Open Source OCR Engine v3.04.00 with Leptonica in /var/www/vendor/thiagoalessio/tesseract_ocr/src/FriendlyErrors.php:74\nStack trace:\n#0 /var/www/vendor/thiagoalessio/tesseract_ocr/src/TesseractOCR.php(39): thiagoalessio\\TesseractOCR\\FriendlyErrors::checkCommandExecution(Object(thiagoalessio\\TesseractOCR\\Command), '', 'Tesseract Open ...')\n#1 /var/www/html/barry_devel/office-db/acct/ajax/ocrInvoiceNo.php(28): thiagoalessio\\TesseractOCR\\TesseractOCR->run()\n#2 {main}\n  thrown in /var/www/vendor/thiagoalessio/tesseract_ocr/src/FriendlyErrors.php on line 74`

#### Environment

* Operating system: `CentOS Linux release 7.8.2003`
* PHP version: `7.3.22`
* Tesseract version: `3.04.00`
* tesseract-ocr-for-php version: `2.9.3`

**Comment by bazzacad** [comment]
Oops never mind, just had to change it to this:
`catch (thiagoalessio\TesseractOCR\UnsuccessfulCommandException $e)`

**Comment by samwilson** [comment]
Note that UnsuccessfulCommandException is used for other errors as well, so it might be necessary to check for the actual 

```php
try {
	$text = $this->ocr->run();
} catch ( UnsuccessfulCommandException $e ) {
	if ( strpos( $e->getMessage(), 'The command did not produce any output' ) !== false ) {
		$text = '';
	}
	throw $e;
}
```
