### ISSUE TITLE
Any idea why i have error?

### ISSUE THREAD

**Issue by s811645** [thiagoalessio/tesseract-ocr-for-php#193]
I do my script with using tesseract with PHP, script **working fine for 1-2-3** requests simultaneously. But, if i send 10+ requests simultaneously its done first 2-3 request, but for next show error:

```
Error! Reading image data from stdin is not available this tesseract version
Required version is 3.03-rc1, actual version is fault

Generated command:
"tesseract" "" "/tmp/ocrEKUVOy"
Error! The command did not produce any output.

====
Returned message:
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
Error! The command did not produce any output.
```
Any idea why this can happen?

I check in Therminal version tesseract  and this show 4.1.4 ([photo](https://prnt.sc/vk9swr))

My Code:
`$this->Imagick->readImageBlob($result);
$this->Imagick->resizeImage(450,120,Imagick::FILTER_CATROM,1);
$this->Imagick->extentImage(450,120,Imagick::FILTER_CATROM,1);

// some other options imagick..
$data = $this->Imagick->getImageBlob();
$size = $this->Imagick->getImageLength();
// read image
$this->tesseract->imageData($data, $size)->lang('eng');
$code = $this->tesseract->run();
$this->tesseract->clearCache();`

**Comment by thiagoalessio** [comment]
This is happening because you seem to be sharing `$this->tesseract` instance, which can lead to this kind of race condition, since temp filenames are stored as instance variables.

To avoid this, my suggestion is to spawn a new instance every time
(replace `$this->tesseract->....` by `(new TesseractOCR())->...`).
