### ISSUE TITLE
Getting the coordinates from recognized text.

### ISSUE THREAD

**Issue by JohniUYS** [thiagoalessio/tesseract-ocr-for-php#201]
Hello, I have a big "map" which has alot of postals, and using TesseractOCR I want to be able to find each postal, and then using a custom search box, find the postal and zoom to it. Everything is done, it recognizes the postals (atleast alot of them) but I don't know how to get the coordinates from each postal.

**Comment by thiagoalessio** [comment]
**hOCR** can help you with that:
- <https://en.wikipedia.org/wiki/HOCR>
- <https://github.com/tesseract-ocr/tessdoc/blob/e972190cac379f3d43f1b7aa7185d7a29389917e/Command-Line-Usage.md#hocr-output>
- <https://github.com/thiagoalessio/tesseract-ocr-for-php/#hocr>
