### ISSUE TITLE
undefined api of userWords

### ISSUE THREAD

**Issue by xiaohui96** [thiagoalessio/tesseract-ocr-for-php#209]
### Expected behavior

I want to use the userWords api in my php file and also
include 'vendor/autoload.php';
use thiagoalessio\TesseractOCR\TesseractOCR;

### Actual behavior

however, the userWords cannnot be called and show cannot find declaration to go to 

### Steps to reproduce the behavior

	<?php
/**
 * Created by IntelliJ IDEA.
 * User: huihui
 * Date: 2021/3/4
 * Time: 10:05
 */
include 'vendor/autoload.php';
use thiagoalessio\TesseractOCR\TesseractOCR;

$imageTempName = "storage/2019202070098实验一/Image_12.jpg";

echo (new TesseractOCR($imageTempName))
    ->userWords('test.txt')
    ->run();

#### Environment

* Operating system: `win10`
* PHP version: `7.2`
* Tesseract version: `5.0`
* tesseract-ocr-for-php version: `2.11`

**Comment by thiagoalessio** [comment]
tesseract 5 is still in alpha ... this kind of weird behavior is to be expected. closing for now, if you experience the same problem once tesseract 5 becomes stable, please feel free to reopen this issue.
