### ISSUE TITLE
only parse particular area of an image

### ISSUE THREAD

**Issue by mindyk** [thiagoalessio/tesseract-ocr-for-php#22]
is it possible to define a specific area within the image to be parsed? like x,y,w,h ?

**Comment by jsneo** [comment]
Use a image editor like Laravel/Intervention to crop the image then parse through Tesseract

$img = Image::make($file);
$img->resize(800,500);	
$img->crop(150,30,280,375);	// function crop(w,h,x,y)
$tesseract = new TesseractOCR($img->dirname . '/' . $img->basename);
$tesseract->setTempDir(self::OCR_PATH);
echo $tesseract->recognize();

**Comment by mindyk** [comment]
yes croping would have been my second take (- : 
thx for you help
