### ISSUE TITLE
Absolute paths for image and TempDir

### ISSUE THREAD

**Issue by GTCrais** [thiagoalessio/tesseract-ocr-for-php#24]
Would have been nice to mention you can't use absolute paths for image location and TempDir. I had this working in "vanilla" PHP in minutes, but then when I tried to integrate it into Laravel, it just wouldn't work. It took me 4 hours of trial and error only to realize

$tesseract = new TesseractOCR("C:\\Program Files\\wamp\\www\\test\\public\\img\\hello.png");

doesn't work, and that only relative paths work.

**Comment by thiagoalessio** [comment]
That's not true, you can check the tests, all of them are running against absolute paths.
