### ISSUE TITLE
Multi-language?

### ISSUE THREAD

**Issue by alexmatveev** [thiagoalessio/tesseract-ocr-for-php#25]
Can I use something like this?
```php
$tesseract->setLanguage('rus+eng');
```

**Comment by thiagoalessio** [comment]
hum, not that I know of ... but you could combine both `.traineddata` to create a new language for tesseract and then use it ;D

**Comment by winkelement** [comment]
Yes it is possible with tesseract 3.03.

> OCR options:
[...]
  -l lang[+lang]        specify language(s) used for OCR
[...]

**Comment by alexmatveev** [comment]
@thiagoalessio Hmm, not a good answer, sorry.
@winkelement Thanks for this. I moving to use tesseract with PHP exec(), without this wrapper.
