### ISSUE TITLE
Warnings in lines 236 and 249

### ISSUE THREAD

**Issue by annnt** [thiagoalessio/tesseract-ocr-for-php#27]
Hi there,

I'm running Tesseract at Linux server, PHP 5.4. I uploaded main class file into classes/TesseractOCR.php, set chmod to 666 on and unfortunatelly it still returning warnings instead of any values from png file.

Here is my code:

require_once 'classes/TesseractOCR.php';
....
$tesseract = new TesseractOCR($file);
$tesseract->setTempDir('/absolute_path_to/temp/'); // temp folder have chmod 777
$tesseract->setWhitelist(range(0,9), '-+.'); // i'm trying to recognize phone numbers
echo $tesseract->recognize();

I tried many ways with path to temp folder (and also without it), but I still gain nothing. I'll very appreciate any help or suggestion; I tried to google out solution but every one comes to set temp folder, which not helps me.

Many thanks in advance.

**Comment by mortezakarimi** [comment]
I've installed tesseract-ocr and the problem was solved with the following command
sudo apt-get install tesseract-ocr
