### ISSUE TITLE
setVerbose 

### ISSUE THREAD

**Issue by collmomo** [thiagoalessio/tesseract-ocr-for-php#28]
I dont wanna see this `Tesseract Open Source OCR Engine v3.02.02 with Leptonica` each time. 
I have added this after line 222 `$command .= " 2>&1 1> /dev/null";`. An option in the constructor or as a setter would be helpful for people annoyed with the message.

**Comment by thiagoalessio** [comment]
makes sense, pull requests are welcome ;D
