### ISSUE TITLE
XY coordinates

### ISSUE THREAD

**Issue by xtuliao** [thiagoalessio/tesseract-ocr-for-php#31]
Hello, how could I retrieve the XY coordinates for each word recognized ?

**Comment by andreuramos** [comment]
https://github.com/thiagoalessio/tesseract-ocr-for-php/issues/22

**Comment by samiles** [comment]
@andreuramos That's about cropping the document first. I think @xtuliao wants to know how to get the location of a given recognised word from a document.

**Comment by maisen20** [comment]
Hello, is there still no function to get the X/Y positions of the recognized words/letters? the answer from @andreuramos is not really an answer to the question of @xtuliao

**Comment by thiagoalessio** [comment]
Is the `hocr` option you are looking for? If not, let me know and we can either reopen this issue or create a new one https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/master/README.md#hocr

**Comment by maisen20** [comment]
oh yes exactly.
thank you very much!

**Comment by Sztuk** [comment]
horc if for html output, it's called tsv, wich contain x, y, w, h, confidence etc.
https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/master/README.md#tsv

**Comment by gidzr** [comment]
eeesh! the output using tsv is a mess of a string.. it looks like a flattened csv with all the heading (or array keys) at the start of the string. But when counting each line, the results are not consistent with columns ruling out a csv.

is there a way of making the api return a usable tsv array, object, or file that makes sense?
