### ISSUE TITLE
Tesseract OCR doesn't work

### ISSUE THREAD

**Issue by CodingAnonymous** [thiagoalessio/tesseract-ocr-for-php#35]
Hi,

I'm trying to install tesseract for php on my webserver. I installed it by downloading the source from github. I want now to install https://github.com/tesseract-ocr/tesseract, but I don't know where to change the $path and where to put this scripts.
Can you please help me?
Thanks!

**Comment by winkelement** [comment]
You need to actually install tesseract-ocr on your server os. Depending which os your server is running on you have different options for installation, like 'apt-get' for Linux, homebrew/macports for os x or you try to compile it from source.

**Comment by thiagoalessio** [comment]
Please take a look on the new release (1.0.0-RC) it allows you to define the location of `tesseract` executable, so you won't need to deal with adding it to `$PATH` anymore.
