### ISSUE TITLE
No errors return nothing with very easy test

### ISSUE THREAD

**Issue by msitruk** [thiagoalessio/tesseract-ocr-for-php#36]
Hello

I try your tesseract-ocr-for-php to decode number in a gif file I follow your instalation instructions and your sample exemple but return me empty result page witheout any errors :

my image file -> http://hpics.li/4e167da
i try to a text in paint file like this but same result ->  http://hpics.li/708e750

My code

```php
require_once './vendor/autoload.php'; //if you are using composer

$tesseract = new TesseractOCR('hello.png');
echo $tesseract->recognize();
```

Maybe I do something wrong ??

Thank in advance for your return.

![test](https://cloud.githubusercontent.com/assets/15679329/10983577/c17a3948-8413-11e5-9f6b-9058712cb2ef.gif)
![test2](https://cloud.githubusercontent.com/assets/15679329/10983576/c178cc20-8413-11e5-8bce-df569e90a92d.jpg)

**Comment by thiagoalessio** [comment]
Not sure what issue you might have faced, but I was also not very happy with this library, so I made a major rewrite of it ... check this out:

```
<?php
require_once 'vendor/autoload.php';

// urls of your images
$img1 = 'https://cloud.githubusercontent.com/assets/15679329/10983577/c17a3948-8413-11e5-9f6b-9058712cb2ef.gif';
$img2 = 'https://cloud.githubusercontent.com/assets/15679329/10983576/c178cc20-8413-11e5-8bce-df569e90a92d.jpg';

// saving images
file_put_contents('img1.jpg', file_get_contents($img1));
file_put_contents('img2.jpg', file_get_contents($img2));

$text1 = (new TesseractOCR('img1.gif'))
    ->psm(7)
    ->run();

// i needed to grab the correct language first, with
// sudo apt-get install-tesseract-ocr-fra
$text2 = (new TesseractOCR('img2.jpg'))
    ->lang('fra')
    ->run();

echo $text1, PHP_EOL, $text2, PHP_EOL;
```

And that is the output:
```
$ php issue-36.php
0578190283
Bunjuurje m'apelle Maxime elj'ai123456759 ans!
```

**Comment by ngocluantdt** [comment]
thank you **thiagoalessio** 
but i has copy your coding and paste my file,it is not work, it return blank. please help me

**Comment by esdebon** [comment]
I have the same problem in windows, I solve it moving the Tesseract-OCR folder inside the xampp folder... PHP haven't access to this if the folder is out of xampp folder.
