### ISSUE TITLE
file_get_contents error 

### ISSUE THREAD

**Issue by Axheladini** [thiagoalessio/tesseract-ocr-for-php#39]
Hello there, 

I have build a small app on my local machine with this class. I had a lot of issues i first run it on my windows machine but i was able to fix them by making changes that i read on discussions here. 
Now i am trying to put my app online on a linux server and i have an issue that is hard to fix. 
When i run the script with command line it works perfectly but on browser it says:  file_get_contents(tempi/1525942339.txt): failed to open stream: No such file or directory in /var/www/html/ocr/TesseractOCR/TesseractOCR.php on line 236

I have tried some of tricks discussed here but non of them worked for me. 

Regards 
Agon

**Comment by bladelin** [comment]
The file is generated by the command "tesseract" 
You can run "tesseract" on your console to make sure that working or not?

Even more, try to break a line to get command for debug as below:

```php
        $command.= '> /dev/null 2>&1';
        // Add this line for debug
        echo $command; die();
        return $command;
```

**Comment by Axheladini** [comment]
On console it works very good, also i am able to wrap the text of a given image on console but not in web browser.

**Comment by bladelin** [comment]
Check your www-data (or other web service owner name) have enough permission writing.
Try to output the error message when run the command :
```php
    protected function execute()
    {
        $this->outputFile = $this->getTempDir().rand();
        exec($this->buildTesseractCommand(), $err);
        print_r($err); // what happened?
    }
```

**Comment by Axheladini** [comment]
It prints an empty Aray:

**Comment by Axheladini** [comment]
![ocr_error](https://cloud.githubusercontent.com/assets/8703041/12143372/70f53fde-b480-11e5-9d46-4b07a4dd170b.png)

**Comment by Axheladini** [comment]
OK Fixed, 

This is what i did. 

1. Created a new directory inside var/www/html dir set  root and www as owner of the dir.
2. Copied all app files to the new dir and again set the ownership of each file and dir to www and root 
3. chmod  775 temp-dir, chmod 775  TesseractOCR/TesseractOCR.php
4. Added this code 

$path = getenv('PATH');
putenv("PATH=$path:/usr/local/bin");

right after

 require_once "TesseractOCR/TesseractOCR.php";

I was stack for days with this. 

Thanks bladelin for your help.

**Comment by big89** [comment]
Same Issue i have on Linux Cpanel. I need urgent help from you guys.

**Comment by big89** [comment]
Hello we need urgent solution with help from anyone. Kindly provide solution from experts.

**Comment by big89** [comment]
Hello Author of this script, i need ur urgent help on this script as it not working at my end. Kindly help me on urgent basis. Thanks

**Comment by big89** [comment]
Hello there,

I have build a small app on my linux shared server and wamp server on local machine also with this class. I had a lot of issues.
Now i am trying to put my app online on a linux server and i have an issue that is hard to fix.
When i run the script with command line it works perfectly but on browser it says:

Warning: file_get_contents(temp/1135767769.txt): failed to open stream: No such file or directory in /home/catchmyd/public_html/ocr_demo/TesseractOCR/TesseractOCR.php on line 255

Warning: unlink(temp/1135767769.txt): No such file or directory in /home/catchmyd/public_html/ocr_demo/TesseractOCR/TesseractOCR.php on line 268

I have tried some of tricks discussed here but non of them worked for me.

Regards
big89

**Comment by samiles** [comment]
@big89 Have the really checked and double checked your file permissions? **Can other PHP scripts open files from that location?** Does Tesseract have permissions? This is very unlikely to be a bug in Tesseract so much as an error in your set up.

**Comment by urfusion** [comment]
getting empty string. Followed

http://stackoverflow.com/questions/34463389/php-tesseractocr-works-only-in-command-line

Code


include 'TesseractOCR.php';
//$obj = new TesseractOCR('text.png');
//var_dump($obj->run());
var_dump (new TesseractOCR('var/www/html/ocr-tesseract/src/text.png'))->run();
//echo dirname(__FILE__);
die('dafs');

    object(TesseractOCR)#1 (8) { ["image":"TesseractOCR":private]=> string(39) "var/www/html/ocr-tesseract/src/text.png" ["executable":"TesseractOCR":private]=> string(9) "tesseract" ["tessdataDir":"TesseractOCR":private]=> NULL ["userWords":"TesseractOCR":private]=> NULL ["userPatterns":"TesseractOCR":private]=> NULL ["languages":"TesseractOCR":private]=> array(0) { } ["psm":"TesseractOCR":private]=> NULL ["configs":"TesseractOCR":private]=> array(0) { } }
