### ISSUE TITLE
file_get_contents error NEW

### ISSUE THREAD

**Issue by big89** [thiagoalessio/tesseract-ocr-for-php#42]
Hello there,

I have build a small app on my linux shared server and wamp server on local machine also with this class. I had a lot of issues.
Now i am trying to put my app online on a linux server and i have an issue that is hard to fix.
When i run the script with command line it works perfectly but on browser it says:

Warning: file_get_contents(temp/1135767769.txt): failed to open stream: No such file or directory in /home/catchmyd/public_html/ocr_demo/TesseractOCR/TesseractOCR.php on line 255

Warning: unlink(temp/1135767769.txt): No such file or directory in /home/catchmyd/public_html/ocr_demo/TesseractOCR/TesseractOCR.php on line 268

I have tried some of tricks discussed here but non of them worked for me.

Regards
big89

**Comment by mustberain** [comment]
i have the same problem, can not figure out what's wrong

**Comment by sherif807** [comment]
The problem might be related to the installation of Tesseract,  on terminal check tesseract by 

$  tesseract -v

make sure the output is close to this output. should have these libs, if its missing the libs then Tesseract is not writing txt file anywhere and thats why it shows can't find it. 

tesseract 3.02.02
 leptonica-1.73
  libjpeg 6b (libjpeg-turbo 1.2.1) : libpng 1.2.49 : libtiff 3.9.4 : zlib 1.2.3

**Comment by mustberain** [comment]
updated and got:

tesseract 3.04.01
leptonica-1.72
libjpeg 8d : libpng 1.6.21 : libtiff 4.0.6 : zlib 1.2.5

Seems good, true? 

This is my code:
`ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require_once 'TesseractOCR/TesseractOCR.php';

$tesseract = new TesseractOCR('Test/images/hello.png');
$tesseract->setTempDir('Test/temp');

echo $tesseract->recognize();`

and get:

Warning: file_get_contents(Test/temp/820949693.txt): failed to open stream: No such file or directory in /**/ocr/tesseract-ocr-for-php/TesseractOCR/TesseractOCR.php on line 236

Warning: unlink(Test/temp/820949693.txt): No such file or directory in 
/**/ocr/tesseract-ocr-for-php/TesseractOCR/TesseractOCR.php on line 249

(masked with **)

**Comment by cwhite92** [comment]
@mustberain your issue is in the following line: `$tesseract->setTempDir('Test/temp');`. You're setting the temp directory to a directory that doesn't exist, and the class is fataling when attempting to read from that directory.

**Comment by big89** [comment]
Hi, Thanks for your reply. The dierctory exist in my code but it not workes
on local system and linux server also. Having issue in that. thanks

**Comment by medienwolf** [comment]
Stuck at the same issue. Directory exists: O:\xampp\htdocs\testbereich\tesseract-ocr-for-php-master\Test\tmp

Even if I create a static File "test.txt" and modify the execute Function to
$this->outputFile = $this->getTempDir().'test';

The output goes without error, but is empty an screen. The file then is beeing removed as well and the crap starts again with file/directory not exists.

**Comment by sherif807** [comment]
Are you sure tesseract is working?  Is it actually reading the image and creating the txt file? Can you try it from the terminal make sure no errors

**Comment by medienwolf** [comment]
Terminal says same error.

**Comment by thiagoalessio** [comment]
Lots of people getting errors with tempDir due to lack of writing permissions ... So I got rid of this whole crap.
Please get the latest version (1.0.0-RC) doesn't use temp files at all ;D
