### ISSUE TITLE
sample image to test

### ISSUE THREAD

**Issue by fajar-khairil** [thiagoalessio/tesseract-ocr-for-php#43]
hi, is there anyone able to extract phone number from this image?

https://s3-ap-southeast-1.amazonaws.com/jualo/user_phones/326113/phone_number20160313-14251-1xbhb3l.jpg

**Comment by thiagoalessio** [comment]
Hello,
Sorry but this is not the right place to ask such questions ... this is intended only to report issues on the library.

I'll close this issue, but if I were you I would try to crop 5 pixels from the bottom of that image (using imagemagick maybe) and run tesseract to get the numbers.
```
 81319521891
```
