### ISSUE TITLE
documentation wrong

### ISSUE THREAD

**Issue by wesleywesley** [thiagoalessio/tesseract-ocr-for-php#44]
documentation seems to be all wrong. 

No run() method (now recognize)
No lang() method (now setLanguage)

etc

**Comment by thiagoalessio** [comment]
it is not wrong, please make sure you are reading the correct version of `README.md`.

Docs of the old version (0.2.1) are here: https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/0.2.1/README.md

But I strongly recommend to always use the latest version (right now is 1.0.0-RC): https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/1.0.0-RC/README.md

**Comment by wesleywesley** [comment]
oops, sorry -- seems composer fetched the old version and I didn't check. thanks!

**Comment by thiagoalessio** [comment]
Yes, was partially my fault as well for that ... just realised that I could have been more specific on the composer.json snippet, to avoid this "minimum-stability" issue:

https://github.com/thiagoalessio/tesseract-ocr-for-php/commit/fd9d4dab95aeb75f83da96396f4fa6bc8f715921
