### ISSUE TITLE
file_get_contents

### ISSUE THREAD

**Issue by dodiyanilesh** [thiagoalessio/tesseract-ocr-for-php#45]
i work in local system xampp in tesseract-ocr,  working properly bt upload online linux server to not working  fiend this error 

Warning: file_get_contents(temp/1135767769.txt): failed to open stream: No such file or directory in /home/catchmyd/public_html/ocr_demo/TesseractOCR/TesseractOCR.php on line 255

Warning: unlink(temp/1135767769.txt): No such file or directory in /home/catchmyd/public_html/ocr_demo/TesseractOCR/TesseractOCR.php on line 268

**Comment by thiagoalessio** [comment]
Yeah, that "No such file or directory" was a pain for many users ... please use the latest version that doesn't use temp files anymore:

```
"require": {
    "thiagoalessio/tesseract_ocr": "1.0.0-RC"
}
```
