### ISSUE TITLE
tesseract-ocr-for-php in laravel 5.2

### ISSUE THREAD

**Issue by buihoang91tin** [thiagoalessio/tesseract-ocr-for-php#46]
I make all step to install this library into laravel 5.2
and I use this into my Controller but it's return null and make nothing.
Could you have me. This is my code

![image](https://cloud.githubusercontent.com/assets/9276526/15278713/84695e38-1b46-11e6-8ad7-5314f48ed5b7.png)

But it's return blank page

**Comment by buihoang91tin** [comment]
Is this oke with tesseract v3.02. 
I dont know how to install v3.03 on windows. Could you help me this issues

**Comment by buihoang91tin** [comment]
I have installed tesseract v3.03 success and run this command is ok "tesseract test.png stdout"
But when I try in laravel PHP is still give me blank page. Could you help me

**Comment by thiagoalessio** [comment]
Hello, I need more information to be able to help ... can you share the image you are trying to recognise?
Also make sure the user who runs PHP has `tesseract` on its `$PATH` (otherwise you have to specify the executable location (https://github.com/thiagoalessio/tesseract-ocr-for-php#-executablepathtotesseract).

**Comment by thiagoalessio** [comment]
didn't hear back from you, closing this issue for now ... if you still have the issue, or if you found a solution and mind to share with others, please feel free to reopen ;D

**Comment by buihoang91tin** [comment]
This is my code 
![image](https://cloud.githubusercontent.com/assets/9276526/16217339/bb0da7f6-379c-11e6-8c59-c256a15a461a.png)

And this is result just show object but not show result
![image](https://cloud.githubusercontent.com/assets/9276526/16217343/cff413b2-379c-11e6-939b-c5de3a9ff151.png)

I dont now how to resolve this

**Comment by buihoang91tin** [comment]
Please reopen my issue. Sorry for later...

**Comment by fredtheryick** [comment]
same problem here.
can someone help us out?

**Comment by fredtheryick** [comment]
I set executable like this
echo (new TesseractOCR(storage_path('app\user_72\capture.jpg')))
    ->executable('C:\Program Files (x86)\Tesseract-OCR\tesseract.exe')
    ->run();

but the result was nothing.

**Comment by VisualTrauma** [comment]
Hi @thiagoalessio , I have the same issue as @fredtheryick.
My code is exaxtly like his.

`$tesseract = new TesseractOCR(public_path('sample.jpg'));
 $tesseract->executable('C:\Program Files (x86)\Tesseract-OCR\tesseract.exe');
 dd($tesseract->run());`

But it returns nothings.

**Comment by fredtheryick** [comment]
Hi @VisualTrauma, maybe this can help you.
$tesseract = (new TesseractOCR(storage_path('app\\' . $file)))
                        ->executable('"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe"')
                        ->lang('eng')
                        ->run();

**Comment by VisualTrauma** [comment]
Thank you @fredtheryick, Can you tell me why does it have to be inside a double qoute? Sorry if this is such a noob question.

**Comment by fredtheryick** [comment]
you are welcome @VisualTrauma 
so actually this code will work too
->executable("C:\Program Files (x86)\Tesseract-OCR\tesseract.exe")
just double quote.

the explanation why is in this link
[http://stackoverflow.com/questions/25305869/when-should-you-use-single-or-double-quotes-in-php](url)
