### ISSUE TITLE
Fix a small bug for set Tesseract language PHP API with chinese

### ISSUE THREAD

**Issue by daijiale** [thiagoalessio/tesseract-ocr-for-php#47]
Hi,thiagoalessio!
     Glad to find and use your project tesseract-ocr-for-php, it  does help me a lot! Thanks for your selfless contribution！
     But during my coding with my ocr-chinese-project, I have used your new API : (new TesseractOCR('xxx.png'))->lang('deu'), your wiki said we need to be specified as 3-character ISO 639-2 language codes.But when I open the ISO 639-2 Page, I find chinese of ISO 639-2 is chi/zho,which is no suit to your API.
      For example: (new TesseractOCR('chinese.png')) ->lang('chi'),  it doesn't work here，And I changed the ISO Code as  (new TesseractOCR('chinese.png')) ->lang('chi_sim'),or, (new TesseractOCR('chinese.png')) ->lang('chi_tra'),the same to the original tesseract langdata , it does work！Maybe the bug of ISO 639-2 is not only appear for chinese！Hope you can pay attention！
      I will fix the wiki and pull a request for your repository later ， hope it can help you！Thanks again！I am a university student from china。 Expect to help for this tesseract-ocr-for-php project and make friend with you！
         
                                                                                                                     Dave  2016.5.25  InChina

**Comment by thiagoalessio** [comment]
@daijiale thanks again ... as I mentioned on the pull request, I made some changes on the text, please take a look and let me know if you agree with the changes: https://github.com/thiagoalessio/tesseract-ocr-for-php#-langlang1-lang2-lang3

**Comment by daijiale** [comment]
Hi thiagoalessio!
       Thanks for your reply,and I have a look the project, it's ok and more accurate when you use the wiki:https://github.com/tesseract-ocr/tesseract/blob/master/doc/tesseract.1.asc#languages
       It's glad to meet you and keep contact ,welcome to more research and questions about OCR.
       Final,I have finished my lated chinese OCR search engine project by using your "tesseract-ocr-for-php" project,if you have an interset,you can take a look at this URL:
https://github.com/daijiale/OCR_FontsSearchEngine


                                                                                               Your Friend :Dave                     
------------------
----------------------------------------------------------------------------------------------------------------------
花名：小枫
联系方式：daijiale@developerclub.cn
学校：电子科技大学
主页：www.daijiale.cn
Github：https://github.com/daijiale



 




------------------ 原始邮件 ------------------
发件人: "Thiago Alessio Pereira";<notifications@github.com>;
发送时间: 2016年7月1日(星期五) 上午6:11
收件人: "thiagoalessio/tesseract-ocr-for-php"<tesseract-ocr-for-php@noreply.github.com>; 
抄送: "枫叶の乐"<daijiale6239@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [thiagoalessio/tesseract-ocr-for-php] Fix a small bug for setTesseract language PHP API with chinese (#47)




@daijiale thanks again ... as I mentioned on the pull request, I made some changes on the text, please take a look and let me know if you agree with the changes: https://github.com/thiagoalessio/tesseract-ocr-for-php#-langlang1-lang2-lang3
