### ISSUE TITLE
install on AWS EC2

### ISSUE THREAD

**Issue by urfusion** [thiagoalessio/tesseract-ocr-for-php#50]
Its not an issue just need support. How can I install it on AWS EC2 ubuntu machine

**Comment by thiagoalessio** [comment]
You can check how I setup a ubuntu trusty to run the tests:
https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/master/.travis.yml

Please next time don't open an issue for a support question, use the IRC channel instead: #tesseract-ocr-for-php on freenode.
