### ISSUE TITLE
not reading image 

### ISSUE THREAD

**Issue by urfusion** [thiagoalessio/tesseract-ocr-for-php#51]
Code 
```

include 'TesseractOCR.php';
//$obj = new TesseractOCR('text.png');
//var_dump($obj->run());
var_dump (new TesseractOCR('var/www/html/ocr-tesseract/src/text.png'))->run();
//echo dirname(__FILE__);
die('dafs');
```

> object(TesseractOCR)#1 (8) { ["image":"TesseractOCR":private]=> string(39) "var/www/html/ocr-tesseract/src/text.png" ["executable":"TesseractOCR":private]=> string(9) "tesseract" ["tessdataDir":"TesseractOCR":private]=> NULL ["userWords":"TesseractOCR":private]=> NULL ["userPatterns":"TesseractOCR":private]=> NULL ["languages":"TesseractOCR":private]=> array(0) { } ["psm":"TesseractOCR":private]=> NULL ["configs":"TesseractOCR":private]=> array(0) { } }

**Comment by turgutsaricam** [comment]
I'm not sure but you're missing a / in front of var/www...

**Comment by urfusion** [comment]
I checked with 
`var_dump (new TesseractOCR('/var/www/html/ocr-tesseract/src/img_name$with@special#chars.png'))->run();`

but same result

string(0) "" object(TesseractOCR)#2 (8) { ["image":"TesseractOCR":private]=> string(63) "/var/www/html/ocr-tesseract/src/img_name$with@special#chars.png" ["executable":"TesseractOCR":private]=> string(9) "tesseract" ["tessdataDir":"TesseractOCR":private]=> NULL ["userWords":"TesseractOCR":private]=> NULL ["userPatterns":"TesseractOCR":private]=> NULL ["languages":"TesseractOCR":private]=> array(0) { } ["psm":"TesseractOCR":private]=> NULL ["configs":"TesseractOCR":private]=> array(0) { } }
Fatal error: Call to a member function run() on null in /var/www/html/ocr-tesseract/src/test.php on line 17

**Comment by thiagoalessio** [comment]
@urfusion which version of tesseract you are using? by the description of your issue it seems to me that you are not using version 3.03 or later.

**Comment by thiagoalessio** [comment]
@urfusion didn't hear back from you, I'm closing this issue ... if you figured out a problem (or something that is not well explained on the README) please share here the solution, might be useful for other people.
