### ISSUE TITLE
tmpfile stream not opened

### ISSUE THREAD

**Issue by mikeetsai** [thiagoalessio/tesseract-ocr-for-php#52]
Hi, 

Its a great library, but Im very new to the TesseractOCR.

I cannot output the TesseractOCR('text.jpg') as the error log of from Apache server saying 
"Warning in pixReadMemJpeg: work-around: writing to a temp file
Error in pixReadMemJpeg: tmpfile stream not opened
Error in pixReadMem: jpeg: no pix returned
Error during processing."

If I used Terminal to Tesseract the text.jpg image, it will works without an issue and the output.txt file is being generated. However, when I do this on the browser to run the php file with the followiing code:
require_once __dir__ . '/vendor/autoload.php';
echo (new TesseractOCR('text.jpg'))
    ->run();

it won't render and produce the error above.
Below was what I did:
I have added full path to the Tesseract executable file.
On the TesseractOCR.php, I have add a full path to the $executable variable (line 20)
private $executable = '/opt/local/bin/tesseract';

Can you please guide me on what does the error mean?, and what am I doing wrong here?

My operating system is:
OSX El Capitan 10.11.4
XAMPP Server
PHP Version 5.6.8

Thanks
Mike

**Comment by thiagoalessio** [comment]
Hello,
Please don't open issues for support requests ... you can use the IRC channel instead (#tesseract-ocr-for-php on freenode).
Cheers.

**Comment by mikeetsai** [comment]
Hi Thiago,

Sorry about the issue posting, and thanks for your advice.

Cheers
Mike
