### ISSUE TITLE
Doesn't display any thing

### ISSUE THREAD

**Issue by ravitdx** [thiagoalessio/tesseract-ocr-for-php#63]
Hello,

I created a simple demo using example. but, it doesn't work .It shows nothing in echo.I ran 
`tesseract images/8055.png test` in command line.
 in the same directory of project,it worked,it added the contents of image "8055.png" to test.txt. Here is my code
`<?php
require_once './TesseractOCR.php';
$ec=new TesseractOCR('./images/text.jpeg');
echo $ec->run();
?>`

I am using wamp server as localhost.Here is my folder structure
`TesseractOCR.php`
`test.php`
`images`
`images/text.jpeg`

What am I doing wrong.Please help.

**Comment by MrCrackR** [comment]
It doesn't work with PHP 7. Change it to 5.6 and it should work fine. Wamp Server 3.0.4 has an option to quickly switch between those versions.

**Comment by luemic** [comment]
Since PHP 5.6 will be at end of life soon (http://php.net/supported-versions.php) I think a downgrad should not be an option in this case.

**Comment by AnaelMobilia** [comment]
@ravitdx You are running the tools on Windows, isn't it ?

If yes, see my pull-request #64 (bad spaces escaping on the executable path)
Regards

**Comment by ravitdx** [comment]
Even on changing the wamp server php version the result is the same.here is the screen shot.
![untitled](https://cloud.githubusercontent.com/assets/18653095/20293172/ed4027a8-ab19-11e6-99cb-d6b77a54d416.png)

the result is not displaying any where.My code is almost same as example then why is it not working.
even if I write this line 

 `echo exec("tesseract text.jpeg test.txt");` 

directly on php,still it doesn't work. Which works in command prompt.Is there still a problem in with PHP configuration in wamp server.

**Comment by AnaelMobilia** [comment]
@ravitdx you need to put the whole path of the application (as it's not on the Windows system PATH var) , eg : (with my pr #64 )
```php
$myOCR->executable('C:\Program Files (x86)\Tesseract-OCR\tesseract.exe');
```
(without my pr #64)
```php
$myOCR->executable('"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe"');
```

or for the exec (remember to protect the space on the path)
```
echo exec('"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe" text.jpeg');
```

Your command need to success on a DOS command prompt, elsely it will not succeed on the exec() function ;-)

**Comment by MrCrackR** [comment]
Yes I put tesseract in PATH manually after I installed it.

**Comment by AnaelMobilia** [comment]
@MrCrackR a good news for sure ! :-)

**Comment by ravitdx** [comment]
I switched from wamp server to Xamp server. Now its working.Thanks.

**Comment by imsocb** [comment]
Hi, I've installed tesseract using composer into my window installed xampp PHP(5.5.37) localhost but it does not work. Everything is run in the 'htdocs/picture' directory folder (version 1.0.0-RC). Tried testing the program with the code below written in test.php but return me blank echo? Please enlighten me. Thanks.
```
<?php
require_once 'vendor/autoload.php'; // Tried omitting this statement however it return me Fatal error: Class 'TesseractOCR' not found in C:\xampp\htdocs\picture\test.php on line 3, therefore added it back but gave blank statement.

echo (new TesseractOCR('text.jpeg'))->run();
?>
```

**Comment by SekharChandraK** [comment]
Hi,
I have installed tesseract-ocr in my windows. when I am using command prompt and executing >tesseract text.jpeg test.txt this command it is working fine, But in php it returns empty ,So any one help me those error. Below is my code:
(new TesseractOCR("asset('images/text.jpeg')"))
			    ->executable('"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe"')
			    ->tessdataDir("C:\Program Files (x86)\Tesseract-OCR")
			    ->run()
Thanks for advance....
