### ISSUE TITLE
Install into Xampp not working gave blank result?

### ISSUE THREAD

**Issue by imsocb** [thiagoalessio/tesseract-ocr-for-php#68]
Hi, I've installed tesseract using composer into my window installed xampp PHP(5.5.37) localhost.  Everything is run in 'htdocs/picture' directory folder (version 1.0.0-RC). Tried testing the program with the code below written in test.php but return me blank echo? Please enlighten me. Thanks.
```
<?php
require_once 'vendor/autoload.php'; // Tried omitting this statement however it return me Fatal error: Class 'TesseractOCR' not found in C:\xampp\htdocs\picture\test.php on line 3, therefore added it back but gave blank statement.

echo (new TesseractOCR('text.jpeg'))->run();
?>
```

**Comment by ravitdx** [comment]
@imsocb 

try run this command in the directory where image was there `tesseract text.jpeg test.txt`. If it shows text in `test.txt`,then In my opinion your path to text.jpeg might be wrong.

**Comment by imsocb** [comment]
Hi thanks for the reply, I've got tesseract working however why is it returning nonsensical output as opposed to what it should be reading in my text.jpeg image? A sample of the image here --> https://www.dropbox.com/s/fhfolj3bsnxms64/text.jpeg?dl=0  I'm rather new to OCR, how do i get it to read the correct text content in the namecard? Thanks

**Comment by ravitdx** [comment]
@imsocb 

I think you took a snap with some camera and used that image.Instead scanning the image with a scanner and using it will produce better results.In the link you gave Binarisation and Rotation / Deskewing are your problems.Apart from problems mentioned in the link,It also depends on font in the image.A font which shows a clear partition between words will produce good results.

**Comment by imsocb** [comment]
@ravitdx It has to be camera images uploaded into the server unfortunately for my case while scanning is not an option. So based on what you have stated (e.g. Binarisation and Rotation/Deskewing isn't these functions built into tesseract?) Or these issues had to solve with additional software or tools installed into xampp environment to improve the reading result? If so can you recommend some of it to improve my reading result? Thank You!

**Comment by KoalaBear84** [comment]
Had the same problems. I had to also include "tesseract.exe" in the command like this:
`->executable('..\tesseract-3.0.4\tesseract.exe')`

**Comment by johnico** [comment]
have same problem with wamp  - got white page

**Comment by thiagoalessio** [comment]
Sorry but this is not the right place to request help, the issues on this repo are meant for reporting bugs on the library.
I'd recommend you post your questions / request for support on #tesseract-ocr-for-php on freenode IRC.

**Comment by jammyproject** [comment]
this code : exec('tesseract raj_OCR.png imagetextname'), i got text file but. on this code : (new TesseractOCR('raj_OCR.png'))->run();
i got this error : 
Fatal error: Uncaught thiagoalessio\TesseractOCR\UnsuccessfulCommandException: Error! The command did not produce any output. Generated command: "tesseract" "raj_OCR.png" C:\Users\SQR PC\AppData\Local\Temp\ocr22DF.tmp Returned message: read_params_file: Can't open PC\AppData\Local\Temp\ocr22DF.tmp Error, could not create TXT output file: Permission denied in C:\xampp\htdocs\rnd_program\composer\vendor\thiagoalessio\tesseract_ocr\src\FriendlyErrors.php:63 Stack trace: #0 C:\xampp\htdocs\rnd_program\composer\vendor\thiagoalessio\tesseract_ocr\src\TesseractOCR.php(24): thiagoalessio\TesseractOCR\FriendlyErrors::checkCommandExecution(Object(thiagoalessio\TesseractOCR\Command), Array) #1 C:\xampp\htdocs\rnd_program\test.php(18): thiagoalessio\TesseractOCR\TesseractOCR->run() #2 {main} thrown in C:\xampp\htdocs\rnd_program\composer\vendor\thiagoalessio\tesseract_ocr\src\FriendlyErrors.php on line 63

please help me as soon as posible

**Comment by jammyproject** [comment]
hi,
i install on tesseract at this location : C:\Program Files (x86) and i set variable on environment variable also. and i install using composer and loaded file using autoload.php ,
so i got above error. please help me. is required to install in xampp also ?
please help me.

**Comment by thiagoalessio** [comment]
@jammyproject I'd like to point to you this project's Gitter: https://gitter.im/thiagoalessio/tesseract-ocr-for-php I'm sure someone there (maybe even myself) would be able to support you with your problem.
