### ISSUE TITLE
Tesseract ocr php in cpanal

### ISSUE THREAD

**Issue by jawwad22** [thiagoalessio/tesseract-ocr-for-php#71]
how can i use your php wrapper in cpanal,i am unable to find any tutorial on it.
Thank you

**Comment by thiagoalessio** [comment]
Sorry but this is not the right place to request help, the issues on this repo are meant for reporting bugs on the library.
I'd recommend you post your questions / request for support on #tesseract-ocr-for-php on freenode IRC.
