### ISSUE TITLE
PHP 7 tesseract-ocr return empty string result

### ISSUE THREAD

**Issue by andrewtan1987** [thiagoalessio/tesseract-ocr-for-php#72]
Hi,

I got the blank result with the following code.
Thanks and appreciate for the advise.

**Code**
require_once 'Tesseract-OCR/vendor/autoload.php';
var_dump(new TesseractOCR('8055.png'));
echo "Expected Result :";
echo (new TesseractOCR('text.jpeg'))->run();

**Result**
object(TesseractOCR)#3 (8) { ["image":"TesseractOCR":private]=> string(8) "8055.png" ["executable":"TesseractOCR":private]=> string(9) "tesseract" ["tessdataDir":"TesseractOCR":private]=> NULL ["userWords":"TesseractOCR":private]=> NULL ["userPatterns":"TesseractOCR":private]=> NULL ["languages":"TesseractOCR":private]=> array(0) { } ["psm":"TesseractOCR":private]=> NULL ["configs":"TesseractOCR":private]=> array(0) { } } 

Expected Result :

**Comment by pockie** [comment]
I had the same problem on Windows 7. First of all i installed [Tesseract OCR](https://github.com/tesseract-ocr/tesseract/wiki) as written in the readme.md. After that I had to change the Path of the Tesseract executable and the path to the tessdir directory.

**Here my code**
require_once "vendor/autoload.php";

$test = new TesseractOCR('text.jpeg');
$test->executable("C:\\Tesseract-OCR\\tesseract.exe");
$test->tessdataDir("C:\\Tesseract-OCR");
$test->lang("deu");

var_dump($test);
$text = $test->run();
echo "Expected Result :";
var_dump($text);

**Result:**
object(TesseractOCR)#2 (8) {  ["image":"TesseractOCR":private]=>string(9) "text.jpeg"
["executable":"TesseractOCR":private]=>string(30) "C:\Tesseract-OCR\tesseract.exe"
["tessdataDir":"TesseractOCR":private]=>string(16) "C:\Tesseract-OCR"
["userWords":"TesseractOCR":private]=>NULL
["userPatterns":"TesseractOCR":private]=>NULL
["languages":"TesseractOCR":private]=>array(1) {
    [0]=>
    string(3) "deu"
  }
["psm":"TesseractOCR":private]=>NULL
["configs":"TesseractOCR":private]=>array(0) { }
}

Expected Result :
string(44) "The quick brown fox
jumps over the lazy
dog,"

**Comment by andrewtan1987** [comment]
I tried the similar code, but still nothing came out. 
Do you mean i need to reinstall Tesseract OCR to the c:\ directory as yours example?

**code**
require_once "Tesseract-OCR/vendor/autoload.php";
$test = new TesseractOCR('text.jpeg');
$test->executable("C:\xampp\htdocs\Tesseract-OCR\tesseract.exe");
$test->tessdataDir("C:\xampp\htdocs\Tesseract-OCR");
$test->lang("deu");
var_dump($test);
$text = $test->run();
echo "Expected Result :";
var_dump($text);

**result**
object(TesseractOCR)#3 (8) { ["image":"TesseractOCR":private]=> string(9) "text.jpeg" ["executable":"TesseractOCR":private]=> string(40) "C: mpp\htdocs\Tesseract-OCR	esseract.exe" ["tessdataDir":"TesseractOCR":private]=> string(27) "C: mpp\htdocs\Tesseract-OCR" ["userWords":"TesseractOCR":private]=> NULL ["userPatterns":"TesseractOCR":private]=> NULL ["languages":"TesseractOCR":private]=> array(1) { [0]=> string(3) "deu" } ["psm":"TesseractOCR":private]=> NULL 
["configs":"TesseractOCR":private]=> array(0) { } }

Expected Result :string(0) ""

**Comment by pockie** [comment]
I think the problem is this line:
$test->executable("C:\xampp\htdocs\Tesseract-OCR\tesseract.exe");

You result of the line is
["executable":"TesseractOCR":private]=> string(40) "C: mpp\htdocs\Tesseract-OCR esseract.exe" 

The t of tesseract.exe is missing as well as the backslash "\". You have to escape the backslash or use single quotes:
`$test->executable("C:\\xampp\\htdocs\\Tesseract-OCR\\tesseract.exe");`

I forgot to insert my code as code in the GitHub editor. My double backslashed were not shown.

**Comment by andrewtan1987** [comment]
Hi,

Thanks for the feedback.
I modified the code, but look like still not working.

require_once "Tesseract-OCR/vendor/autoload.php";
$test = new TesseractOCR('text.jpeg');
$test->executable("C:\\xampp\\htdocs\\Tesseract-OCR\\tesseract.exe");
$test->tessdataDir("C:\\xampp\\htdocs\\Tesseract-OCR");
$test->lang("deu");
var_dump($test);
$text = $test->run();
echo "Expected Result :";
var_dump($text);

object(TesseractOCR)#3 (8) { ["image":"TesseractOCR":private]=> string(9) "text.jpeg" ["executable":"TesseractOCR":private]=> string(43) "C:\xampp\htdocs\Tesseract-OCR\tesseract.exe" ["tessdataDir":"TesseractOCR":private]=> string(29) "C:\xampp\htdocs\Tesseract-OCR" ["userWords":"TesseractOCR":private]=> NULL 
["userPatterns":"TesseractOCR":private]=> NULL 
["languages":"TesseractOCR":private]=> array(1) { [0]=> string(3) "deu" } ["psm":"TesseractOCR":private]=> NULL 
["configs":"TesseractOCR":private]=> array(0) { } } 

Expected Result :string(0) ""

**Comment by pockie** [comment]
In your first comment you used the file 8055.png and now you use my file text.jpeg. Is that the problem?

**Comment by andrewtan1987** [comment]
Hi, I found the problem, after removed $test->lang("deu"); and it working... Thanks so much.. really appreciate it...
