### ISSUE TITLE
Any idea 

### ISSUE THREAD

**Issue by hstorc** [thiagoalessio/tesseract-ocr-for-php#73]
Any Idea how to extract the serial number ("H94344456") from [this image](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTMZJ8QPFoU2jB3iO4qTHxitgnaSr4UGzxbCqqDs_Aur_fO0dgG)?

**Comment by JoanManuelH** [comment]
If all images have the same size you can crop that area and then run the script

**Comment by hstorc** [comment]
than Joan.
I ended up using imageMagick to remove all other colors but the red color
and then run the OCR. That works very well indeed.
The only problem is the the digit "4" in [this bill.](https://i.ytimg.com/vi/qha38IXg2qs/maxresdefault.jpg)

**Comment by thiagoalessio** [comment]
Sorry but this is not the right place to request help, the issues on this repo are meant for reporting bugs on the library.
I'd recommend you post your questions / request for support on #tesseract-ocr-for-php on freenode IRC.
