### ISSUE TITLE
Didn't find any solution how to use the tesseract ocr package?

### ISSUE THREAD

**Issue by priya3593** [thiagoalessio/tesseract-ocr-for-php#78]
I have download whole package form here https://github.com/thiagoalessio/tesseract-ocr-for-php.git
Could you please explain in detail, how will it work as I am not able to find any solution according to README.md file instructions.
Any help would be greatful!

**Comment by thiagoalessio** [comment]
Sorry but this is not the right place to request help, the issues on this repo are meant for reporting bugs on the library.
I'd recommend you post your questions / request for support on #tesseract-ocr-for-php on freenode IRC.
