### ISSUE TITLE
Problem with TesseractOCR.php

### ISSUE THREAD

**Issue by TariGit** [thiagoalessio/tesseract-ocr-for-php#80]
Hello, I have used composer to compile the library, and I have problems with taking the resources of Tesseract.exe, I dont know if I have to write the languages ​​I have to use or whats the problem.

First I have intalled tesseract in program files and i have added to the path, second i have made the process of composer and last i have made the php.

This is the error:

`Parse error: syntax error, unexpected '[' in C:\xampp\htdocs\test\vendor\thiagoalessio\tesseract_ocr\src\TesseractOCR.php on line 48`

And this is the code:

```
require __DIR__ . '/vendor/autoload.php';
$tesseract =new TesseractOCR('Tickets/IMG_1892.JPG');
$tesseract ->lang('spa');
echo $tesseract->run();
```

**Comment by thiagoalessio** [comment]
Hello @TariGit seems that you are using an old PHP version. I'd recommend you to use 5.4 or greater.
