### ISSUE TITLE
I use this in windows wamp but doesn't work for me showing blank page

### ISSUE THREAD

**Issue by Ahmadkhan12345566** [thiagoalessio/tesseract-ocr-for-php#83]
How can i use it on windows wamp i installed the tesseract ocr  .i make indx.php inside tesseract-ocr-for-php
and use your simple code but doesn't work for me how can i use this any help?

**Comment by Demers94** [comment]
I'm having a similar issue. It's working from the command line, but not from my PHP script using WAMP.

Here's my code : 
    
    $instance = new TesseractOCR('image.png');
    echo $instance->run();

There is only a blank page with no output.

If I do `$instance->buildCommand()` and run the output from the command line, in the same working directory, it works just fine and I get the correct text output.

Thanks for your help!

**Comment by zoilomora** [comment]
Does not show you any error messages?

**Comment by Ahmadkhan12345566** [comment]
yes doesn't show any error

**Comment by Ahmadkhan12345566** [comment]
I am trying this code now
<?php
require_once(__DIR__."/vendor/autoload.php");

echo(new TesseractOCR('a.jpg'))->run();
?>
But it shows blank page

**Comment by Ahmadkhan12345566** [comment]
I am trying this code 
<?php
require_once(__DIR__."/vendor/autoload.php");

echo(new TesseractOCR('a.jpg'))->run();
?>
but its shows blank page

**Comment by zoilomora** [comment]
Can you try to reach that line of code?
- Write a text at the end
- Testing with ``print_r ($var, true);``

**Comment by Demers94** [comment]
Hi @zoilomora 

Thanks for the fast reply.

If I run this code : 

```
require_once 'vendor/autoload.php';

$instance = new TesseractOCR('image.png');

$text =  $instance->run();

print_r($text, true);
```

All I get is a blank page.

If I replace `print_r()` by a `var_dump()` instead, it shows me this : 

    C:\wamp64\www\demo\index.php:9:string '' (length=0)

**Comment by Ahmadkhan12345566** [comment]
same results

**Comment by Ahmadkhan12345566** [comment]
How can I use this on a windows machine? any proper guide line?

**Comment by zoilomora** [comment]
Sorry for the delay.

Having [tesseract-ocr](https://github.com/tesseract-ocr/tesseract/wiki/4.0-with-LSTM#400-alpha-for-windows) installed and included in the **Windows Path**. You would have to run anywhere in **cmd** and also in PHP.

Example:
```
$obj = new \TesseractOCR('image.png');
$text = $obj->run();
```

**Comment by Ahmadkhan12345566** [comment]
**I set the path** 
![path](https://user-images.githubusercontent.com/20639894/28498469-1774963c-6f53-11e7-9be2-bd8a74263440.png)
**.and when i run your code**
```
$obj = new \TesseractOCR('image.png');
$text = $obj->run();
```
**it shows**
![browser](https://user-images.githubusercontent.com/20639894/28498483-5b12861a-6f53-11e7-9ecd-50d536a91d01.png)
**...Working fine form cmd.**
is anything i am doing wrong?

**Comment by zoilomora** [comment]
The **Windows Path** has to go to ``C:\Program Files (x86)\Tesseract-OCR``, where the file **tesseract.exe** is located.

- Change the value.
- Restart the **Operating System**.
- Try again.

**Comment by Ahmadkhan12345566** [comment]
I check this before can you explain this, please ..
# What he wants to explain I didn't understand

IMPORTANT: Make sure that the tesseract binary is on your $PATH. If you're running PHP on a webserver, the user may be not you, but _www or similar. If you need, there is always the possibility of modify your $PATH:

```
$path = getenv('PATH');
putenv("PATH=$path:/usr/local/bin");
```
i am on a server wamp but i didn't not understand what he said

**Comment by Ahmadkhan12345566** [comment]
I didn't found a single help from anywhere on windows ...
There are questions on StackOverflow but not answered ...

**Comment by zoilomora** [comment]
That information is valid for a **Linux Server** but:

`IMPORTANT: Make sure that the tesseract binary is on your $PATH.`

![paths](https://user-images.githubusercontent.com/4701956/28501840-f1b94d9c-6fe4-11e7-82a7-c992861af644.png)

**Is what you need to do now.**

**Comment by Ahmadkhan12345566** [comment]
I am doing the same ...
but
![github10](https://user-images.githubusercontent.com/20639894/28501913-57e9c546-6f9b-11e7-8871-f89d1e8605dd.png)

**Comment by thiagoalessio** [comment]
https://github.com/thiagoalessio/tesseract-ocr-for-php#-executablepathtotesseract

**Comment by Ahmadkhan12345566** [comment]
Thanks For your help but doesn't work for me.
t tried ->executable
But same results blank page
zoilomora thanks for your time ....

**Comment by Ahmadkhan12345566** [comment]
I copied the # (Tesseract-OCR) dir to my project # dir
and make _index.php inside_ the Tesseract-OCR dir # copy _vendor_ **dir** in Tesseract-OCR 
this works fine for me
