### ISSUE TITLE
Doesn't work on Win7 with wamp

### ISSUE THREAD

**Issue by aboelmor** [thiagoalessio/tesseract-ocr-for-php#84]
Dears,

I have instantiated a new PHP project and ran composer require thiagoalessio/tesseract_ocr from cmd.
My project has the following structure:

MyProject
-Source Files
--vendor
---composer
---thiagoalessio
---autoload.php
--composer.json
--composer.lock
--index.php

I used the following code in index.php:
`<?php
require_once "../../thiagoalessio/tesseract_ocr/src/TesseractOCR.php";
echo (new TesseractOCR('tests/text.png'))->run();
?>`

The paths here are correct and I have no errors on the browser but the result is empty. I even tried other images in different location but I got the same result.

can you please shed the light on a solution please.

Thank you

**Comment by mohamadriyaz** [comment]
did u get the desired output?
