### ISSUE TITLE
Can't read Data from png

### ISSUE THREAD

**Issue by aboelmor** [thiagoalessio/tesseract-ocr-for-php#85]
Dears,

I have the attached file with Arabic digits in it (some call it hindu numbering as well)
![capture3](https://user-images.githubusercontent.com/19220278/28717011-a4782b08-73a8-11e7-9f99-5b4768fdf454.PNG)

I cannot read it even if I use "hin" or "ara" language. I get a result i.e. "4ماكة؟؟1" which has nothing to do with the data in the file.

I even added the entire numbers to the user-words file and referenced it as follows:
`$test->userWords("Path/To/user/words/eng.user-words");`
I tried it for ara and hin as well !! but nothing changed

here's my code:
`<?php
require_once "../../thiagoalessio/tesseract_ocr/src/TesseractOCR.php";
$test = new TesseractOCR('Path/To/Image/capture3.png');
$test->executable("Path/Tesseract-OCR/tesseract.exe");
$test->tessdataDir("Path/Tesseract-OCR");
//$test->userWords("Path/Tesseract-OCR/tessdata/eng.user-words");
$test->lang("en");
var_dump($test);
$text = $test->run();
echo "Expected Result :";
var_dump($text);
?>`

Please note that my code is working for normal english but it doesn't read arabic data!!

Any help is appreciated

**Comment by zoilomora** [comment]
Is a Tesseract-OCR problem, not the PHP library.

Try to run the OCR command directly with the bash. When you get the correct result try to translate it to the library code.

**Comment by thiagoalessio** [comment]
@aboelmor hum, I guess the problem is the size and/or quality of your image.

I ran it against the image you provided directly on the CLI, and here is what I got:
```
$ tesseract issue85.PNG -l ara stdout
٦ » لما ٦ . ٤ ٣ لإ ا
```

Getting a bigger image seems to work better (although the recognition was not 100% correct, there are some "dots" present on the image but absent on the output)

![arabic-3](https://user-images.githubusercontent.com/190616/28736827-01e1d8b4-73ec-11e7-8d73-0cdb75aab3a5.png)

CLI:
```
$ tesseract arabic-3.png -l ara stdout
اللغة العرسة
```

PHP:
```
$ cat test.php
<?php
require_once './vendor/autoload.php';

echo (new TesseractOCR('arabic-3.png'))
    ->lang('ara')
    ->run();

$ php test.php
اللغة العرسة
```

**Comment by aboelmor** [comment]
thanks thagoalessio for the prompt reply,

I tried a bigger image, but it didn't read the numbers ! It reads the letters correctly as you mentioned with a slight difference but it doesn't read number. here's my image

![capture2](https://user-images.githubusercontent.com/19220278/28741928-59233d6e-742a-11e7-9562-4b6f0c1df368.PNG)

Any idea ?
