### ISSUE TITLE
eastern-arabic numerals are not supported

### ISSUE THREAD

**Issue by aboelmor** [thiagoalessio/tesseract-ocr-for-php#86]
Dears,

As an enhancement to the library, I want to suggest adding the eastern-arabic numerals:
١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩
which correspond to U+0660 through U+0669

Thank you

**Comment by thiagoalessio** [comment]
Hi @aboelmor that is a nice suggestion for tesseract itself: https://github.com/tesseract-ocr/tesseract
This PHP wrapper doesn't do much in this regard ... it will return whatever is recognized by tesseract.
