### ISSUE TITLE
Example files

### ISSUE THREAD

**Issue by ionutanin** [thiagoalessio/tesseract-ocr-for-php#92]
Hello, 

First of all thank you for developing and sharing this.
I'm mostly a frontend developer and don't have experience on backend at all.
Can you please post an example file?

Here is what I did: I've created a index.php, included the php class and then used your exemple:
echo (new TesseractOCR('text.png'))->run();
then I ran it in wamp and the page is blank. I've expected to see the output.

Tesseract is installed, I can successfully run tesseract text.png from command prompt and it saves the output to txt file. The tesseract is included in path.

I had a guzzle warning that is no longer supported and I should use instead guzzlehttp but I suppose it installed it anyway (I've ignored this)

I'm trying to reproduce this functionality on windows10 using wamp, php5.6.31

Thanks.

**Comment by thiagoalessio** [comment]
The functional tests can serve as an example of how the library should work, take a look here:
https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/master/tests/FunctionalTests.php
and the environment preconditions:
https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/master/.travis.yml
