### ISSUE TITLE
Get text from image

### ISSUE THREAD

**Issue by Blacksky13** [thiagoalessio/tesseract-ocr-for-php#93]
Hi! I can`t take text from such image. Can somebody help me?
![test](https://user-images.githubusercontent.com/25365058/33051395-60114bc8-ce72-11e7-93ea-78c1db56d94e.jpeg)

**Comment by thiagoalessio** [comment]
tesseract alone won't be able to distinguish the text from the noise, take a look on this similar issue:
https://github.com/thiagoalessio/tesseract-ocr-for-php/issues/91#issuecomment-342290510
