### ISSUE TITLE
Missing Namespace

### ISSUE THREAD

**Issue by ZeZiNhOo** [thiagoalessio/tesseract-ocr-for-php#99]
I am trying to use your nice work with Symfony.
It would be nice to provide a name space allowing to use the class directly without an ugly

require_once './vendor/thiagoalessio/tesseract_ocr/src/TesseractOCR.php';

This information also misses in the README file...
That said, I am not a very good programmer ;-)

**Comment by thiagoalessio** [comment]
Hi, you don't need to use this ugly require ;D
You can just use the global namespace, like so:

```php
<?php
require_once './vendor/autoload.php';
echo (new \TesseractOCR('image.png'))->run();
```

And following your advice, I also improved a bit the examples on the README, to make it more obvious.

**Comment by KirillRyzhkov** [comment]
I installed library in my project folder and created file index.php with
```
<?php
use thiagoalessio\TesseractOCR\TesseractOCR;
echo (new TesseractOCR('text.png'))
->run();
```
I get error
PHP Fatal error:  Uncaught Error: Class 'thiagoalessio\\TesseractOCR\\TesseractOCR' not found in

Also Eclipse shows
The import thiagoalessio\TesseractOCR\TesseractOCR cannot be resolved

How can I solve this problem?

**Comment by thiagoalessio** [comment]
which version of the library you have installed? As I mentioned before, namespaces were added only on version `2.0`.

**Comment by KirillRyzhkov** [comment]
I installed it like this locally in a project folder
```
{
	"require" : {
		"thiagoalessio/tesseract_ocr" : "*"
	}
}
```

**Comment by thiagoalessio** [comment]
just post your `composer.lock` file please

**Comment by KirillRyzhkov** [comment]
{
    "_readme": [
        "This file locks the dependencies of your project to a known state",
        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file",
        "This file is @generated automatically"
    ],
    "content-hash": "c0cb2b6fa1e6d04e355fec91e2fda292",
    "packages": [
        {
            "name": "thiagoalessio/tesseract_ocr",
            "version": "2.0.0",
            "source": {
                "type": "git",
                "url": "https://github.com/thiagoalessio/tesseract-ocr-for-php.git",
                "reference": "0e91eb357946c71fadc92d9493c87d56dee63d96"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/thiagoalessio/tesseract-ocr-for-php/zipball/0e91eb357946c71fadc92d9493c87d56dee63d96",
                "reference": "0e91eb357946c71fadc92d9493c87d56dee63d96",
                "shasum": ""
            },
            "require-dev": {
                "phpunit/phpunit": "^6.5"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "thiagoalessio\\TesseractOCR\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "Apache-2.0"
            ],
            "authors": [
                {
                    "name": "thiagoalessio",
                    "email": "thiagoalessio@me.com"
                }
            ],
            "description": "A wrapper to work with Tesseract OCR inside PHP.",
            "keywords": [
                "OCR",
                "Tesseract",
                "text recognition"
            ],
            "time": "2017-12-10T21:41:18+00:00"
        }
    ],
    "packages-dev": [],
    "aliases": [],
    "minimum-stability": "stable",
    "stability-flags": [],
    "prefer-stable": false,
    "prefer-lowest": false,
    "platform": [],
    "platform-dev": []
}

**Comment by thiagoalessio** [comment]
yeah, you have the correct version.

But I just noticed now that your code snippet lacks the autoloader inclusion:

It should be something like that:
```php
<?php
require_once __DIR__.'/vendor/autoload.php';

use thiagoalessio\TesseractOCR\TesseractOCR;
echo (new TesseractOCR('text.png'))
->run();
```

Please let me know if that solves your issue ;D

**Comment by KirillRyzhkov** [comment]
Thanks, it worked now, although Eclipse shows error that it can't resolve the namespace

**Comment by thiagoalessio** [comment]
Nice, glad it works ;D

Well, I don't know much about Eclipse (except that is heavy 😆 ) ... I'm myself a vim user.
Maybe that could help: https://stackoverflow.com/questions/4589960/why-is-eclipse-php-not-recognizing-namespace-declarations

**Comment by KirillRyzhkov** [comment]
Thank you, I checked it as well and I have settings for 7.1. But at least it works, so I will leave this error for now
